gardener/machine-controller-manager

- .gitignore
- Dockerfile
- Makefile
- README.md
- docs/README.md
- docs/deployment/kubernetes.md
- docs/design/README.md
- docs/development/local_setup.md
- docs/development/testing_and_dependencies.md
- docs/usage/instance.md
- docs/usage/instance_deployment.md
- docs/usage/instance_set.md
- docs/usage/prerequisite.md
- kubernetes/aws-instance-class.yaml
- kubernetes/deployment.yaml
- kubernetes/deployment/clusterrole.yaml
- kubernetes/deployment/clusterrolebinding.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/instance-deployment.yaml
- kubernetes/instance-set.yaml
- kubernetes/instance.yaml
- kubernetes/secret.yaml
- pkg/controller/instance.go
- pkg/driver/driver_aws.go
1. Updated kubernetes directory to make examples more consistent
2. AWS Provider config can be passed as a secret
3. Modified Makefile and Dockerfile 
4. Added documentation
> Updated documentation and examples

- Makefile
- kubernetes/deployment/control-cluster-role-binding.yaml
- kubernetes/deployment/control-cluster-role.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/deployment/target-cluster-role-binding.yaml
- kubernetes/deployment/target-cluster-role.yaml
- pkg/controller/deployment.go
- pkg/controller/machine_util.go
1. Better validation for ClassKind
2. Made examples more consistent
3. Changed log levels while adding machine deployment
> Better validation and made examples consistent

- Makefile
- kubernetes/deployment/deployment.yaml
Updated docker image to point to our public gardener repository.
> Machine-Controller-Manager Release 0.1.0

- docs/development/new_cp_support.md
- kubernetes/aws-machine-class.yaml
- kubernetes/openstack-machine-class.yaml
- pkg/apis/machine/validation/awsmachineclass.go
- pkg/apis/machine/validation/openstackmachineclass.go
- pkg/controller/machine_safety.go
- pkg/controller/openstackmachineclass.go
- pkg/driver/driver_openstack.go
This PR fills up the interfaces required to support safety controller for openstack to avoid creating orphan VMs.
> Added OpenStack support for safety controller

- docs/design/README.md
- docs/development/new_cp_support.md
- kubernetes/azure-machine-class.yaml
- pkg/apis/machine/validation/azuremachineclass.go
- pkg/controller/machine_safety.go
- pkg/driver/driver_azure.go
This commit adds azure support in safety controller.
> Added Azure support for safety controller

- kubernetes/gcp-machine-class.yaml
- pkg/apis/machine/validation/gcpmachineclass.go
- pkg/controller/machine_safety.go
- pkg/driver/driver_aws.go
- pkg/driver/driver_azure.go
- pkg/driver/driver_gcp.go
- pkg/driver/driver_openstack.go
This PR Adds support for GCP in safety controller.
This closes Issue: https://github.com/gardener/machine-controller-manager/issues/3
> Added GCP support for safety controller

- pkg/controller/deployment.go
- pkg/controller/machineset.go
Allow deletion of frozen machineSet and machineDeployments.
> Allow deletion of frozen machineSet and machineDeployments

- .ci/check
- .ci/integration-tests
- .ci/sample-objects/aws/machine.yaml
- .ci/sample-objects/aws/md-scale-down.yaml
- .ci/sample-objects/aws/md-update.yaml
- .ci/sample-objects/aws/md.yaml
- .ci/test
- .gitignore
- cmd/machine-controller-manager/app/controllermanager.go
- pkg/options/helpers.go
- pkg/options/types.go
- pkg/util/client/leaderelectionconfig/config.go
- pkg/util/configz/configz.go
- pkg/util/controller/client_builder.go
- pkg/util/labels/labels.go
- pkg/util/taints/taints.go
- pkg/util/workqueue/prometheus/prometheus.go
This is a sample PR to test the working of CI
> Testing CI

- .ci/pipeline_definitions
- CODEOWNERS
- MAINTAINERS.md
This enables use of the Github codeowners feature
https://help.github.com/articles/about-codeowners/
> Replace MAINTAINERS.md by CODEOWNERS

- pkg/driver/driver_azure.go
Azure driver's VM creation logic consisted of two steps, NIC creation and VM creation respectively. When creation of NIC succeeds and VM creation fails, it leads to creation of orphan NICs. This commit fixes that.
Resolves: https://github.com/gardener/machine-controller-manager/issues/73
> Bugfix: Azure NIC and VM creation made into a transaction

- .ci/test
- pkg/util/taints/taints_test.go
Unit tests are executed via .ci/test as well as via make test.
> Enabled and integrated unit tests in build.

- pkg/controller/machine.go
- pkg/controller/machine_test.go
Changes made:
1. modified machine.go to use constants for NodeConditionType and ConditionStatus
2. modified machine.go to include NodeConditionType, ConfigOK, so that it is not ignored. More checks to be added later
3. Added isHealthy testcase in machine_test.go
> Unit Testcase in machine.go for checking health of the machine

- pkg/controller/machine.go
- pkg/controller/machine_test.go
This commit includes:
- change in updateMachineConditions method [in machine.go] to return error
- Test for udpateMachineConditions in machine.go
> Added test for updateMachineConditions in machine.go

- pkg/apis/machine/validation/awsmachineclass.go
- pkg/driver/driver_aws.go
> Handling IOPs field when creating volume of type AWS io1

- pkg/controller/machine_safety.go
- pkg/controller/machine_safety_test.go
PR includes:
1. check in machine_safety.go if machineDeployment exists for machineSet
2. test for unfreezeMachineSetsAndDeployments in machine_safety.go
> Added test for unfreezeMachineSetsAndDeployments in machine_safety.go

- cmd/machine-controller-manager/app/controllermanager.go
- cmd/machine-controller-manager/controller_manager.go
- kubernetes/deployment/deployment.yaml
- pkg/controller/controller.go
- pkg/handlers/health.go
- pkg/handlers/health_test.go
The following PR replaces the existing health endpoint to make it more useable.
Closes #50.
> Liveliness endpoint

- docs/proposals/excess_reserve_capacity.md
This is a proposal to address the issue: https://github.com/gardener/machine-controller-manager/issues/26
> [WIP] Proposal for excess reserve capacity

- pkg/apis/machine/types.go
- pkg/apis/machine/v1alpha1/types.go
- pkg/controller/controller_utils.go
- pkg/controller/machine.go
- pkg/controller/machine_safety.go
- pkg/controller/machine_util.go
- pkg/driver/driver_aws.go
Fixes typos present in the code.
Fixes #
```improvement operator
NONE
```
> Fixed typos

- .ci/test
- .gitignore
- Makefile
This shows code coverage while running test.
```improvement operator
Displays code coverage after running unit tests
```
> Make test displays code coverage while running tests

- .ci/integration-tests
- pkg/controller/metrics.go
- pkg/driver/driver_alicloud.go
Removed issues in the CI pipeline
Fixes #
> Removed linting issues, and update CI script

- cmd/machine-controller-manager/app/options/options.go
- pkg/controller/machine_safety.go
- pkg/options/types.go
Minor fixes
Fixes #
```improvement operator
```
> Minor fixes

- docs/proposals/external_providers_grpc.md
Proposal for GRPC based implementation of Cloud Providers for MCM
Fixes #
```improvement operator
```
> Proposal for GRPC based implementation of Cloud Providers for MCM

- .ci/integration-tests
Fixes #171
```improvement operator
Bugfix - Integration tests wait for cleanup of all providers; Integration tests now adds support for Azure
```
> Bugfix integration tests cleanup; Integration tests add support for Azure

- pkg/driver/driver_alicloud.go
Work around hostname issue in Alibaba
Fixes #187
> Inject hostname for userdata for Alicloud provider when creating machine

- pkg/driver/driver_alicloud.go
- pkg/driver/driver_alicloud_test.go
Fix the bug when node name is not recognized by Machine
Fixes #187
** To Reviewers **:
PR #188 is not elegant. This PR is better.
> Using default hostname in Alicloud.

- .ci/pipeline_definitions
Fixes #
```improvement operator
```
> Updated CI test image to support python 3.6

- kubernetes/machine_classes/azure-machine-class.yaml
- pkg/apis/machine/validation/azuremachineclass.go
Fixes some print statements and documentations w.r.t Azure machine class validation
Fixes #217 
```improvement operator
NONE
```
> Fix: Renamed AdminUserName to AdminUsername

- .ci/integration-tests
Ignore azure integration tests due to a known bug in lock-aquire caused due to network issue. This issue is being worked upon upstream
Fixes #
```improvement operator
```
> Ignore Azure IT

- pkg/driver/driver_alicloud.go
Fixes #235 
```improvement operator
AliCloud driver now generates the correct ProviderID on machine-object.
```
> Bugfix: AliCloud now generates the right provider-ID

- pkg/controller/machine_safety.go
Fixes #238 
```improvement operator
Bug fixed in machineSet unfreeze logic
```
> Bugfix: MachineSet unfreeze now goes through

- pkg/controller/controller_suite_test.go
- pkg/controller/controller_utils.go
- pkg/controller/machineset.go
- pkg/controller/machineset_test.go
**What this PR does / why we need it**:  This PR adds few tests for machine-set.
Fixes #
```improvement operator
Enhanced unit-test coverage for machineset controller
```
> Unit tests for machineset controller

- pkg/controller/drain.go
**What this PR does / why we need it**: This PR slightly improves the efficiency of the drain by eliminating unnecessary calls to API-server.  There seem to be more probable improvements in the drain[distrupting core-logic] which can be entertained in subsequent PR. These changes could also be integrated while switching to drain-lib supported by the community.
Fixes #
```improvement operator
Drain logic makes use of lesser API calls
```
> Improvement in drain logic

- pkg/controller/deployment.go
- pkg/controller/machine.go
- pkg/controller/machineset.go
- Moved frequent logs to higher log levels
- Removed unwanted comment message
Fixes #
```improvement operator
NONE
```
> Improved logs and comments

- pkg/controller/drain.go
- pkg/controller/drain_test.go
- pkg/controller/machine.go
Fixes #
```improvement operator
Bugfix: Allows force deletion of pods who have no controllers backing them
```
> Split force deletion

- pkg/controller/deployment_util.go
- pkg/controller/machineset.go
A minor change of logging of NodeTemplate updates.
Fixes # 
```improvement operator
```
> Log NodeTemplate updates

- docs/development/local_setup.md
Some minor documentation fix for local dev setup.
```improvement operator
NONE
```
> Updated local dev setup guide

- pkg/controller/drain.go
**What this PR does / why we need it**: This PR improves the log while draining - adds node-name wherever needed.
```improvement operator
```
> Improve logs while draining

- pkg/controller/drain.go
Improved logs to display pod/PV drain times
Fixes #309 
```improvement operator
```
> Further improved logs while draining

- pkg/driver/driver_azure.go
Eliminates creation of orphan NICs when VM creation fails
Fixes #298 
```improvement operator
Bugfix: Eliminates creation of orphan NICs when VM creation fails
```
> Bugfix: Eliminates creation of orphan NICs when VM creation fails

- pkg/controller/secret_test.go
**What this PR does / why we need it**: 
Fixes #
```improvement operator
```
> Unit-tests for PR #319

- pkg/controller/machine.go
Fixes #
```improvement operator
Bugfix: Attempt deletion of node only if it is present and isn't blank
```
> Bugfix: Attempt deletion of node only if it isn't blank

- pkg/controller/machine.go
Reverts gardener/machine-controller-manager#322
> Revert "Bugfix: Attempt deletion of node only if it isn't blank"

- pkg/controller/machine.go
Better handling of error conditions
Fixes #
```improvement operator
Bugfix: Delete node only if nodeName isn't empty
```
> Bugfix: Delete node only if nodeName isn't empty

- pkg/controller/machine.go
Fixes #
```improvement operator
Bugfix: Delete node only if nodeName isn't empty
```
> Rel-0.21.1-dev: Delete node only if nodeName isn't empty

- pkg/controller/machine_util_test.go
**What this PR does / why we need it**:  Negative unit-tests for #256 
Fixes #263 
```improvement operator
Negative tests for taints, annotations and labels support
```
> Few negative unit-tests for the feature supporting taints, annotations and labels

- pkg/controller/drain.go
- pkg/controller/machine_safety.go
- pkg/controller/machineset.go
- pkg/controller/machineset_test.go
Fixes #337 
```improvement operator
Fixes leaks in Go Routines leading to CPU wastage
```
> Closed open channels

- pkg/driver/driver_azure.go
Deletes any infra resources before returning error on machine create
Fixes #345 
```improvement operator
Deletes any infra resources before returning error on machine create
```
> Delete infra resources before returning error on create

- pkg/controller/machineset.go
Fixes #363 
```improvement operator
Bugfix: Allow deletion of machine without status.currentStatus.phase
```
> Allow deletion of machine without status.currentStatus.phase

- pkg/controller/deployment.go
- pkg/controller/machineset.go
Fixes #357 
```improvement operator
Bugfix: Remove dependency on MachineClass while deleting MachineDeployment/MachineSets
```
> Bugfix: Remove dependency on MachineClass while deleting MachineDeployment/MachineSets

- pkg/controller/deployment.go
- pkg/controller/machine_safety.go
Further, hide safety-controller logs and log when Machinedeployment is processed.
Fixes # 
```improvement operator
```
> Improved logs

- pkg/driver/driver_aws.go
Default instanceVolumes deleteOnTermination to true
Fixes #
```improvement operator
Set deleteOnTermination flag to true while deleting the VMs in AWS. 
```
> Default instanceVolumes deleteOnTermination to true

- README.md
Signed-off-by: Swapnil Mhamane <swapnil.mhamane@sap.com>
Adds ci badge to have quick access to build status on master branch 😄 
Fixes #
```improvement operator
NONE
```
> Add ci master build status badge

- README.md
- cmd/machine-controller-manager/app/controllermanager.go
- go.mod
- pkg/controller/machine_bootstrap_token.go
- pkg/controller/machine_util_test.go
- pkg/driver/driver_azure.go
- vendor/k8s.io/klog/README.md
Update the build badge
Fixes #
```improvement operator
NONE
```
> Update the build badge

- kubernetes/machine_classes/azure-machine-class.yaml
- pkg/apis/machine/types.go
- pkg/apis/machine/v1alpha1/types.go
- pkg/apis/machine/v1alpha1/zz_generated.conversion.go
- pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/machine/zz_generated.deepcopy.go
- pkg/driver/driver_azure.go
- pkg/openapi/openapi_generated.go
on the network interfaces of machines.
More details: https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli
Accelerated network enabled better network performance for Azure machines, see [here](https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli#benefits)
Fixes partly #https://github.com/gardener/gardener-extension-provider-azure/issues/55
See [here](https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli#confirm-that-accelerated-networking-is-enabled)
```improvement user
Machine Controller Manager support now Azure machines whose network interface …
```
> Azure: Allow to enable accelerated networking

- pkg/driver/driver_aws.go
Fixes #445 
```improvement operator
Bugfix: Continue with VM deletion when data disk doesn't exist for AWS.
```
> Bugfix: Delete VM when disk doesn't exist

- docs/development/cp_support_new.md
Update instructions to add new cp support
Fixes #
```improvement operator
```
> Update instructions to add new cp support

- cmd/machine-controller-manager/app/options/options.go
- pkg/util/provider/app/options/options.go
This PR is temporary fix #490. Needs a permanent fix in future.
Fixes #490 
```improvement developer
Increased default concurrent worker syncs from 5 --> 10
```
> Increased concurrent worker syncs from 5 --> 10

- pkg/driver/driver_aws.go
AWS: Allow deletion of VMs on get images (or) modify instance failure.
Fixes #
```noteworthy user
AWS: Allow deletion of VMs even on get images / modify instance failures.
```
> AWS: Allow deletion of VMs even on get images / modify instance failures.

- README.md
- docs/FAQ.md
- docs/design/README.md
**What this PR does / why we need it**: Improve documentation with FAQ.
Fixes https://github.com/gardener/machine-controller-manager/issues/121 #529 
```improvement operator
Improved documentation with FAQ.md
```
> Improve documentation with FAQ

- README.md
Fixes #
```improvement operator
None
```
> Migration note for OOT providers

- .ci/pipeline_definitions
This PR updates the image of ci-pipeline
Fix the integration tests pipeline step.
```Traceback (most recent call last):
File "/cc/utils/cli.py", line 230, in <module>
main()
File "/cc/utils/cli.py", line 99, in main
parsed.func(parsed)
File "/cc/utils/cli.py", line 219, in function_runner
function(*function_args)
File "/cc/utils/cli/gardener_ci/config.py", line 54, in attribute
raw = _retrieve_model_element(cfg_type=cfg_type, cfg_name=cfg_name).raw
File "/cc/utils/cli/gardener_ci/config.py", line 25, in _retrieve_model_element
cfg_factory = ctx().cfg_factory()
File "/usr/local/lib/python3.8/dist-packages/ctx.py", line 183, in cfg_factory
factory = _cfg_factory_from_secrets_server()
File …
```
> updated the ci pipeline image

- kubernetes/crds/machine.sapcloud.io_scales.yaml
This PR updates the scales CRD to v1 . The update was left earlier.
Fixes #
```other operator
NONE
```
> Updates scales crd to v1

- docs/development/integration_tests.md
- kubernetes/crds/machine.sapcloud.io_machinesets.yaml
- kubernetes/deployment/out-of-tree/deployment.yaml
- pkg/test/integration/common/framework.go
- pkg/test/integration/common/helpers/cluster.go
- pkg/test/integration/common/helpers/handling_files.go
- pkg/test/integration/common/helpers/machine_resources.go
Improves IT framework
Fixes #638 
```other operator
NONE
```
> improves IT suite 

- .docforge/manifest.yaml
Change docforge manifest
Fixes #
```other operator
None
```
> Change docforge manifest

- pkg/util/provider/machinecontroller/machine_safety.go
- pkg/util/provider/machinecontroller/machine_safety_test.go
* made orphan collection code more readable
* added more test cases
Fixes #
```other operator
NONE
```
> Refactor Orphan collection logic

- docs/FAQ.md
- docs/development/cp_support_new.md
- docs/development/integration_tests.md
- docs/proposals/external_providers_grpc.md
This PR fixes broken links in the Gardener website.
```improvement developer
NONE
```
> Fixed broken links 01.2022

- docs/FAQ.md
- docs/development/integration_tests.md
- docs/development/local_setup.md
- docs/development/machine_error_codes.md
- docs/docs/apis.md
This PR fixes broken links
```doc developer
NONE
```
> Fixed broken links - 02.2022

- pkg/controller/deployment_util.go
Cherry pick of #685  
Fixes #
```bugfix user
typo stopping scaleDown disabling during cluster rollout is fixed
```
> Automated cherry pick of #685: typo corrected

- pkg/util/provider/drain/drain.go
> Nit: Fix a typo

- docs/FAQ.md
This PR updates the FAQ
Now the mechanism to escape garbage collection is described in the FAQ
Fixes #
```other operator
NONE
```
> FAQ updated related to garbage collection

- docs/development/machine_error_codes.md
- pkg/util/provider/drain/drain.go
> Nit: Fix typos

- pkg/util/provider/machinecontroller/machine.go
In Azure the call to create a VM is async. The operation is periodically polled until Azure reports a successful VM creation. Because of the delay between polling periods it may be that the node has joined the cluster by the time the creation op succeeds. In that case, because of #645 the VM would be immediately deleted and a brief loop of VM "thrashing" starts where MCM will retry creating the machine with the same name and be immediately deleted. The extra condition added here prevents this behaviour.  
Fixes #
```other operator
Stale node detector skips marking a node as stale if the node name and machine name are equal.
```
> Update stale node check to check if node names are equal

- pkg/util/provider/machinecontroller/machine.go
/kind/bug
Cherry pick of #707 on rel-v0.44.
#707: Update stale node check to check if node names are equal
**Release Notes:**
```other operator
Stale node detector skips marking a node as stale if the node name and machine name are equal.
```
> [rel-v0.44] Automated cherry pick of #707: Update stale node check to check if node names are equal

- .ci/pipeline_definitions
- Dockerfile
To fix the vulnerability present in the old image binaries
Fixes #
```improvement operator
Base image updated to alpine `v3.15.4` and build image to golang `1.17.9`.
```
/invite @kon-angelo
> Alpine and golang image updated

- docs/FAQ.md
This PR fixes broken links.
Fixes #
```doc developer
NONE
```
> Fixed broken links - 05.2022

- docs/todo/outline.md
Adds TODO documentation in docs.
Fixes #
```other operator
NONE
```
> Added docs/todo/outline.md 

- .docforge/manifest.yaml
- docs/FAQ.md
- docs/development/cp_support_new.md
- docs/development/cp_support_old.md
- docs/documents/apis.md
- docs/proposals/external_providers_grpc.md
This PR removes the overrides from the manifest file and adds titles to the md files instead.
Fixes #
```doc developer
NONE
```
> Removed overrides from manifest file

- README.md
- docs/documents/apis.md
This PR fixes broken links in the repository.
Fixes #
```doc developer
NONE
```
> Fixed broken links

- .ci/pipeline_definitions
- Dockerfile
Fixes #
```other developer
go version updated to 1.19.4 in pipeline and Dockerfile
```
> Upgrade to go 1.19.4

- CODEOWNERS
- CONTRIBUTING.md
Fixes #
```other operator
NONE
```
> Updated code-owners, contributing file

- docs/documents/apis.md
This PR fixes broken links.
Fixes #
```doc developer
NONE
```
> Fixed broken links - 2023.03

- kubernetes/deployment/out-of-tree/deployment.yaml
- pkg/controller/metrics.go
- pkg/metrics/metrics.go
- pkg/util/provider/machinecontroller/metrics.go
- pkg/util/provider/metrics/metrics.go
Fixes #
```other developer
Removed dead metrics code and refactored the remaining metrics code
```
> Refactor metrics code

- docs/FAQ.md
Fixes #
```other operator
NONE
```
> Updated/added entries to FAQ

- docs/development/integration_tests.md
- pkg/test/integration/common/framework.go
This PR updates the integration tests doc to make it a bit more clear to a first time reader 
Fixes #
```other operator
```
> Minor updates to integration tests doc

- pkg/util/provider/machinecontroller/machine_util.go
following done:
* rate-limited removal logs are improved
* drainNode log is printed only after confirming node's presence, and if node absent that is also logged as warning
This helps in better debugging.
Fixes #
```other operator
NONE
```
> Improved rate-limited machine removal logs

- .ci/pipeline_definitions
- Dockerfile
- go.mod
- go.sum
- vendor/github.com/onsi/ginkgo/v2/extensions/table/deprecated.go
- vendor/modules.txt
Update go lang version to `1.21.4`.
Fixes #
```other operator
NONE
```
> Update go to `1.21.4`

- pkg/util/provider/machinecontroller/machine.go
Fixes #892
```bugfix developer
NONE
```
> nil fix in MC.updateNodeToMachine

- cmd/machine-controller-manager/app/controllermanager.go
- pkg/controller/controller_utils.go
- pkg/controller/deployment_rolling.go
- pkg/controller/deployment_sync.go
- pkg/controller/deployment_util.go
- pkg/controller/machineset.go
- pkg/controller/machineset_util.go
- pkg/util/provider/machinecontroller/machine_util.go
Fixes #905
```other developer
NONE
```
> Diagnostics Logs for MCM

- go.mod
- go.sum
- pkg/util/k8sutils/version.go
- pkg/util/provider/app/app.go
- pkg/util/provider/drain/drain.go
- pkg/util/provider/machinecontroller/controller.go
Updates the package, which has been on v3 for a while. The API and behaviour in our cases are the same.
Fixes #
```other operator
```
> Update `github.com/Masterminds/semver` to v3

- Makefile
This PR provides a flag to specify target platform for the docker image
Fixes #921 
```other operator
```
> Fix docker image

- docs/FAQ.md
This PR fixes broken links in the documentation and updates the styling of the `README.md` file.
Fixes #
```doc developer
NONE
```
> Fixed broken links - 2024.10

- docs/FAQ.md
- docs/documents/_index.md
- docs/proposals/_index.md
- docs/todo/_index.md
This PR transfers the frontmatter from the website manifest to the repo.
Fixes #
```doc developer
NONE
```
> Transfer Frontmatter - 2025.02

- pkg/util/provider/drain/drain.go
We recently came across a bug where MCM kept on trying to evict a pod even though the pod was already evicted.
What we found was that MCM constructs a list of pods it wants to evict and keeps on trying to evict them until the eviction call succeeds.
This logic today fails when the pod eviction is done by another actor. It was seen that MCM does not fetch the pod again from the cache and hence does not see that the pod is already evicted
This PR adds a check to see if the pod is already evicted before it continues eviction attempts
Fixes #974 
```bugfix operator
Fix a bug where MCM does not check if a pod has already been evicted before reattempting eviction …
```
> Check if pod still exists before further eviction is attempted

- cmd/machine-controller-manager/app/options/options.go
- pkg/util/provider/app/options/options.go
This PR adds input validations for data passed to MC via command line arguments
Fixes #
```other operator
```
> Add validation for flags passed to machine controller

- docs/documents/apis.md
- kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml
- kubernetes/crds/machine.sapcloud.io_machines.yaml
- kubernetes/crds/machine.sapcloud.io_machinesets.yaml
- pkg/openapi/openapi_generated.go
This PR runs `make generate` to regenerate apis and crds
Fixes #
```other operator
```
> run make generate

- .ci/pipeline_definitions
PR enables auto assignment of security and compliance tickets.
Fixes #
/invite @aaronfern @unmarshall @thiyyakat @thiyyakat
```other operator
NONE
```
> Updating cnudie labels
