gardener/machine-controller-manager

pkg/apis/machine/register.go, pkg/apis/machine/v1alpha1/register.go
After integrating Azure the new structs have not been added to the scheme. The node-controller-manager cannot report events on those objects.
=> Add AzureMachineClass[List] to Scheme

kubernetes/deployment/clusterrole.yaml
After integrating Azure the example ClusterRole for the node-controller-manager has not been updated.
=> Add `AzureMachineClass` resource to ClusterRole

pkg/driver/driver_aws.go
- In the `AWSMachineClass` object it is possible to define tags which are applied to the VM.
- If no tag with key `Name` has been defined in the class, the AWS driver will default it to the name of the machine object it acts on.
- Otherwise, the value provided in the class is taken.
closes #10
=> AWS VMs "Name" tag defaults to machine object name

kubernetes/aws-machine-class.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/validation/awsmachineclass.go, pkg/driver/driver_aws.go, pkg/openapi/openapi_generated.go
Mentioned in the node-controller-manager's TODO document (point 12).
Although the AWS SDK calls it "availability zone" the user is expected to enter an AWS region.
=> Change the term 'availabilityZone' to 'region' in AWSMachineClass

pkg/driver/driver_aws.go
All of the AWS machines created under MachineDeployment were assuming same tag-name due to the bug.
=> Fix buggy tags for AWS driver

kubernetes/openstack-machine-class.yaml, pkg/driver/driver_openstack.go
According to other infrastructures an tags block can be now specified in the machine class:
```
tags:
tag1: tag1-value 
tag2: tag2-value
```
=> Added OpenStack metadata/tags support for machine creation

Makefile, cmd/machine-controller-manager/app/controllermanager.go, cmd/machine-controller-manager/app/options/options.go, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/types.go, pkg/apis/machine/validation/awsmachineclass.go, pkg/apis/machine/validation/azuremachineclass.go, pkg/apis/machine/validation/gcpmachineclass.go, pkg/apis/machine/validation/machine.go, pkg/apis/machine/validation/machinedeployment.go, pkg/apis/machine/validation/machineset.go, pkg/apis/machine/validation/openstackmachineclass.go, pkg/controller/controller.go, pkg/controller/deployment.go, pkg/controller/machine.go, pkg/controller/machine_safety.go, pkg/controller/machineset.go, pkg/driver/driver.go, pkg/driver/driver_aws.go, pkg/driver/driver_azure.go, pkg/driver/driver_fake.go, pkg/driver/driver_gcp.go, pkg/driver/driver_openstack.go, pkg/options/types.go
Added support for a new safety sub-controller
The safety controller avoids creation/running of orphan VMs or machine objects. The three features supported by it.
1. Freezes any machineSet/machineDeployment whose machine objects backing exceeds by a large number.
2. Terminates any orphan VMs on cloud provider for the accessable machineClass objects (current-cluster).
3. Freezes any machineSet/machineDeployment whose machines fail to show up after configured timeout.
Currently the safety controller only supports AWS.
The drain, health, and machine-set timeouts are now configurable via flags.
=> Integration of safety controller

pkg/controller/controller_utils.go, pkg/controller/machine.go
Added an annotation on machine creation which indicates its priority while scaling down of machine-set replicas. The lower its priority, the higher its chances for getting scheduled for deletion during scale down. The default priority is 3.
This feature can be used while integrating cluster auto-scaler to indicate machines targeted for deletion by cluster autoscaler.
=> Machine prioritization while scale down

pkg/controller/machine.go, pkg/controller/machine_safety.go, pkg/controller/machineset.go, pkg/driver/driver.go, pkg/driver/driver_aws.go, pkg/driver/driver_azure.go, pkg/driver/driver_fake.go, pkg/driver/driver_gcp.go, pkg/driver/driver_openstack.go
Azure earlier treated all VM resources (VMs, NIC, Disks) as a single resource and atomically created/deleted them in the driver interface. This caused issues when the controller crashes, during deletions. To fix this, now GetVMs interface checks for all resources instead of just VMs.
=> BugFix: Azure now tracks of all VMs resources

pkg/controller/machine.go, pkg/driver/driver_azure.go
- The drain nodes logic was reading an older version of the object while making drain call, there by fetching the wrong last operation timestamp. This lead to forceful draining of nodes. This was fixed by updating the updateMachineStatus method to return the new object instead of the old one.
- Azure didn't handle error handling for cases when NIC wasn't created properly. This commit fixes that by embedding appropriate error messages when errors occur in Azure driver machine creation logic.
Resolves: https://github.com/gardener/machine-controller-manager/issues/67
=> Bugfix: Draining issue and Azure error handling

cmd/machine-controller-manager/cli/managevm.go, pkg/driver/driver_openstack.go
Create machines even if there are two images with the same name in the tenant.
=> Fixed openstack multi image creation problem

pkg/apis/machine/validation/gcpmachineclass.go
Machine Class validation for GCP had a spelling mistake while validation due to which machines deployed with SSD backing failed. This commit fixes the bug.
Resolves: https://github.com/gardener/machine-controller-manager/issues/83
=> Bugfix: Fixes bug while deploying machines backed by SSD on GCP

Gopkg.lock, pkg/controller/machine_safety.go, pkg/controller/machine_safety_test.go, vendor/github.com/onsi/ginkgo/extensions/table/table.go, vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
Added ginkgo sub-package github.com/onsi/ginkgo/extensions/table to vendoring.
Added bugfixes in a couple of places in machine_safety.go to handle machinesets without machinedeployments.
=> Some unit tests for safety controller.

pkg/controller/machine.go
Fix: Reconcile the machines that are in "Failed" state also because they might become "Ready" after a while
=> Issue #78: Update failed machine object state

pkg/controller/machine.go, pkg/controller/machine_test.go
- This PR changes machine health check logic to only watch out for issues of Kubelet or diskPressure.
- Changes on Kubelet configuration to handle memory/disk pressure are to be done on Gardener next
Partially Resolves: https://github.com/gardener/machine-controller-manager/issues/95
=> Machine health considers - Kubelet and DiskPressure status

pkg/apis/machine/v1alpha1/types.go, pkg/controller/deployment_machineset_util.go, pkg/controller/deployment_sync.go, pkg/controller/machine.go
The summary of machineobjects which are not in "Running" phase is propagated to machineset and machinedeployment. Decision pending on:
1. which fields are required to propagate
1. Under what conditions should the summary be propagated
=> Propagate machine status to machineset and machinedeployment

pkg/controller/deployment.go, pkg/controller/machine_safety.go, pkg/controller/machineset.go
MachineSet currently gets frozen unexpectedly during major scale-down. That was because safety-controller does not have any means to understand if it's genuine scale-down or over-shooting of the machine-objects. 
I am solving the issue, by reducing the scope of the Freeze-function, where now it applies only while scale-up and scale-down works as it is even when MachineSet is Frozen. Open for suggestions.
=> Fix unexpected freeze during scale-down 

pkg/controller/controller.go, pkg/controller/machine_safety.go
Adds an event handler to trigger orphan VM checking before deletion of machine object.
=> Invoked orphan VM handler on machine object deletion

.ci/pipeline_definitions
Users expect to write american english in pipeline definitions.
Therefore rename "finalise" to "finalize"
=> Use american english for pipeline definition

pkg/apis/machine/validation/gcpmachineclass.go
Solution: Only the root disk on GCP has an image requirement. You can
attach other block storage without a source image, and this change
allows for that.
=> Problem: can't add non image disk on GCP

pkg/controller/deployment_progress.go, pkg/controller/deployment_util.go, pkg/controller/machine.go, pkg/controller/machine_util.go, pkg/controller/machineset.go
- There were several places where machine objects were re-enqueued unwantedly
- This lead to several reconcilation loops and objects being updated frequently
- This commit removes any such code
Fixes #
```noteworthy operator
Removed any unwanted re-enqueuing/re-conciliation of machine objects  
```
=> Removed any unwanted re-enqueuing of machine objects

pkg/controller/controller.go, pkg/controller/metrics.go
Add instructions to integrate custom Prometheus metrics.
Start with a first basic metric about the amount of managed machines.
Fixes #
Checkout, build and run locally. Curl the mcm metrics endpoint  and grep for 'mcm_' metrics.   
``curl localhost:10258/metrics | less``
```improvement operator
The mcm has now support to integrate custom Prometheus metrics. A metric to expose the amount of managed machines is already integrated.
```
=> Add support for custom Prometheus metrics.

kubernetes/openstack-machine-class.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/validation/openstackmachineclass.go, pkg/driver/driver_openstack.go, pkg/openapi/openapi_generated.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/urls.go
Add allowed address pair with the Calico IPPool subnet to OpenStack ports during server creation to allow communication between worker without additional IPinIP protocol.
Fixes #141 
See https://github.com/gardener/gardener/issues/160 for the gardener related changes.
=> Add Calico subnet to OpenStack ports

README.md
**What this PR does / why we need it**: Updating to README to include the cluster-api reference in it.
Fixes #
```improvement operator
```
=> Adding cluster-api ref in readme

.ci/pipeline_definitions
On a new release of the machine-controller-manager, the release notes should be published to the internal slack channel `k8s-mcm`
Fixes #
We have requested a [slack bot](https://kubernetes.slack.com/apps/A0F7YS25R-bots?next_id=0) on the `Kubernetes` workspace to publish release notes to the public `gardener` channel but it was rejected by one of the Kubernetes slack admins.  
```improvement operator
NONE
```
=> post release notes to internal slack channel

cmd/external-aws-client/external-aws-client.go, pkg/external/driver/aws/aws.go, pkg/grpc/infraclient/infraclient.go
External driver handles restsart of MCM gracefully, instead of crashing.
Fixes #
```improvement operator
```
=> External driver handles restsart of MCM gracefully

kubernetes/machine_classes/alicloud-machine-class.yaml, pkg/apis/machine/validation/alicloudmachineclass.go, pkg/driver/driver_alicloud.go
Fix the issue that panic happens when AccessKeyID or AccessKeySecret is empty for alicloud.
Fixes #145
NONE
NONE
=> Fix panic issue when AccessKeyID or AccessKeySecret is empty

.ci/test, Makefile, cmd/machine-controller-manager/app/options/options.go, pkg/controller/controller.go, pkg/controller/controller_suite_test.go, pkg/controller/machine.go, pkg/controller/machine_safety.go, pkg/controller/machine_safety_test.go, pkg/controller/machine_test.go, pkg/fakeclient/client.go, pkg/options/types.go
We need to enhance the freeze logic of safety-controller when APIServers are not reachable to freeze the machine controller from doing any wrong/unwanted reconcilations
Fixes #155 
The commits have been split into the following
1. (Un)freezing of machine controller based on APIServer availability - Actual logic for freezing
2. Controller test suite now supports control and target clients, Testing Framework now supports faking of object tracker returns/delays - Enhancements to testing framework
3. Added test cases for machine controller freezing - Adding unit test cases to test changes.
```improvement operator
(Un)freezing of machine controller based on APIServer …
```
=> Enhancement freeze logic

.ci/integration-tests, Makefile, cmd/machine-controller-manager/app/options/options.go, pkg/controller/controller_suite_test.go, pkg/controller/machine.go, pkg/controller/machine_safety.go, pkg/controller/machine_test.go, pkg/options/types.go
The machine-controller-manager used a single configurable knob (machine-health-timeout) to configure both creation and health timeouts. However, this reduced flexibility as both timeouts used a single knob. Now the creation and health timeouts have been split into two different configurable knobs.
Fixes #176 
Commits have been split into 3 for easy of the reviewer. Only look at last 3 commits, as the rest are old commits from another PR which is in review.
1. Cleanup of existing timeouts from int to duration type
2. Actual changes to accommodate splitting of creation and health timeouts
3. Updated test cases to test changes correctly. No new tests were added, as there were …
=> Splitting of health timeout into creation and health timeouts

.ci/integration-tests
Just fixes a wrong log message which made me wonder at first.
Machine objects are checked in the control cluster and not in the target cluster.
=> Fixed misleading/wrong log message

pkg/controller/machine_test.go, pkg/driver/driver_openstack.go
Currently the error is not handled for the create call to openstack. Added fix for the same.
Fixes #181 
Tested by injecting dummy error instead of actual landscape because of its unavailability.
```improvement operator
```
=> Error handling during openstack create() call. Fixes #181

.ci/pipeline_definitions
The CI pipelines now use Golang version 1.11.2
Fixes #
```improvement operator
```
=> Updated pipeline definition to use Golang 1.11.2

docs/development/local_setup.md
The doc for local setup has the wrong path to managevm, which, apparently, was renamed.
```improvement user
Fixes documentation while running CLI client
```
=> indicate proper path to managevm cli

cmd/machine-controller-manager-cli/main.go
The output from the `managevm` CLI didn't have space between the machine ID and Name, mixing them together. This fixes it.
Before:
```
$ managevm ...
Machine id: packet:///75b74ee6-d7af-4a65-82ca-73c895cd50a9/ff1c19e9-550f-4cce-b80a-eabca6a86a97Name: ff1c19e9.packethost.net
```
After:
```
$ managevm ...
Machine id: packet:///75b74ee6-d7af-4a65-82ca-73c895cd50a9/ff1c19e9-550f-4cce-b80a-eabca6a86a97
Name: ff1c19e9.packethost.net
```
=> Add linefeed

kubernetes/deployment/deployment.yaml
The sample deployment.yaml contained a --namespace=default parameter
that was overwriting the actual configured namespace.
The sample deployment.yaml has a parameter `--namespace=$(CONTROL_NAMESPACE)` where users can set the control namespace for the machine-controller-manager. But later in the file the parameter is statically set to `--namespace=default`, effectively overwriting the setting of the user. This is confusing and should probably be cleaned up.
Fixes #
```
NONE
```
=> Fix sample deployment.yaml

pkg/controller/controller_suite_test.go, pkg/controller/controller_utils.go, pkg/controller/deployment_rollback.go, pkg/controller/deployment_rollback_test.go, pkg/controller/deployment_rolling.go, pkg/controller/deployment_rolling_test.go, pkg/controller/deployment_util.go, pkg/controller/machine.go, pkg/controller/machine_safety_test.go, pkg/controller/machine_test.go, pkg/driver/driver_alicloud_test.go
Fixes #120 
```noteworthy operator
Prefers scheduling of pods on newer machines during roll-outs
```
=> Optimise pod handling in machine updates

.ci/pipeline_definitions
> We have just released Go 1.11.5 and Go 1.10.8 to address a recently reported security issue. We recommend that all users update to one of these releases (if you’re not sure which, choose Go 1.11.5).
>
> This DoS vulnerability in the crypto/elliptic implementations of the P-521 and P-384 elliptic curves may let an attacker craft inputs that consume excessive amounts of CPU.
>
> These inputs might be delivered via TLS handshakes, X.509 certificates, JWT tokens, ECDH shares or ECDSA signatures. In some cases, if an ECDH private key is reused more than once, the attack can also lead to key recovery.
>
> The issue is CVE-2019-6486.
n/a
n/a
```improvement operator …
```
=> Upgrade golang version to 1.11.5

docs/development/new_cp_support.md, pkg/controller/machine.go, pkg/controller/machine_safety.go, pkg/driver/cmi-client.go
Updated documentation and code while adding new provider support using new gRPC services.
Fixes #215 
```improvement operator
NONE
```
cc: @afritzler
=> Updated documentation to adapt to new gRPC services

pkg/controller/metrics.go
Fixes #224 
```improvement operator
Fixes panic issue while fetching metrics of failed machines
```
cc: @fsniper
=> Fixes panic issue while fetching metrics on failure machines

pkg/driver/driver_azure.go
Fixes #231 
```improvement operator
Removes null pointer exception on Azure
```
=> Bugfix: Removed null pointer exception on Azure

pkg/controller/machine.go, pkg/controller/machine_safety.go, pkg/driver/cmi-client.go
Fixes issues on machine-controller-manager while integrating with `cmi-client` branch.
Fixes #
```improvement operator
```
=> Fixed empty machineID issue and enhanced print statements

.ci/pipeline_definitions
https://golang.org/doc/go1.12
Fixes #
```improvement operator
The golang version has been upgraded to `v1.12.0`.
```
=> Update golang to 1.12.0

.ci/check
Currently `$ make check` fails with:
```
package github.com/golang/lint/golint: code in directory /tmp/build/d56d9853/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
```
`github.com/golang/lint/golint` is replaced by `golang.org/x/lint/golint`. See [golang/lint#45](https://github.com/golang/lint/issues/415).
Fixes #
```improvement operator
NONE
```
=> Fix make check

pkg/controller/controller_suite_test.go, pkg/controller/machine_test.go
Fixes merge conflicts in unit tests for machine
Fixes #
```improvement operator
NONE
```
=> Fixes merge conflicts in unit tests for machines

.ci/integration-tests, .ci/sample-objects/aws/md-scale-up.yaml, .ci/sample-objects/az/md-scale-up.yaml, .ci/sample-objects/gcp/md-scale-up.yaml, .ci/sample-objects/os/md-scale-up.yaml, pkg/controller/machine_safety.go
Integration tests now checks for freezing and unfreezing of machine-sets due to overshooting replicas
Fixes #246 
```improvement operator
Added safety controller cases in integration tests
```
=> Added safety controller cases in integration tests

pkg/controller/machine.go, pkg/controller/machine_test.go
We realized existing machine-objects were not picking up the node-label. This PR fixes that bug.
Fixes #
```improvement operator
Bugfix: Existing machine-objects now adopts the node-label.
```
=> Bugfix: Existing machine-object now adopts node-label

pkg/controller/secret_util.go
MCM does not add its finalizer to alicloud machine class secrets, this is now fixed.
```improvement operator
The machine-controller-manager does now correctly add its finalizer to Alicloud machine class secrets.
```
=> Fix missing finalizers on alicloud machine class secrets

.ci/pipeline_definitions, docs/development/testing_and_dependencies.md, docs/usage/machine.md, docs/usage/machine_deployment.md, docs/usage/machine_set.md, docs/usage/prerequisite.md, kubernetes/crds.yaml, pkg/controller/deployment_machineset_util.go, pkg/controller/machine_util.go, pkg/controller/machine_util_test.go
- Add additionalPrinterColumns to example CRDs. I also want to add them to the CRDs in gardener/gardener-extensions (gardener/gardener-extensions#99). It will be useful to have them for faster ops.
- Update golang to 1.12.5
Fixes #
```improvement operator
NONE
```
=> Add additionalPrinterColumns to example CRDs

pkg/controller/deployment_rollback_test.go, pkg/controller/deployment_rolling_test.go, pkg/controller/machine_util_test.go
Unit-tests seems to be flaking because current taint-support does not guarantee the order of taints. This PR fixes a couple of tests which are assuming the ordered taints.
Fixes #
```improvement operator
```
=> Fix unit-tests

pkg/driver/driver_aws.go
Avoid panic in the AWS driver if invalid AMI is supplied.
Fixes #278 
```improvement operator
Fix panic in AWS driver if AMI not found.
```
=> Fix panic in AWS driver if AMI not found.

.ci/pipeline_definitions
Update test image to use golang@1.12.6. The pipeline_definition for a PR is taken from the master branch, not from the PR itself. 
Required for #280.
Fixes #
@ccwienk 
```improvement operator
NONE
```
=> Update test image to use golang@1.12.6

pkg/driver/driver_openstack.go
Handle broken VM status, when they are in non-active state, e.g.
```
$ openstack server list --limit 3
+--------------------------------------+---------------------------------------------------+--------+--------------------------------+---------------------+----------+
| ID                                   | Name                                              | Status | Networks                       | Image               | Flavor   |
+--------------------------------------+---------------------------------------------------+--------+--------------------------------+---------------------+----------+
| c7892fcc-9ac9-4317-9e44-5672dbbdac23 | shoot--garden--soil-cpu-worker-z1-b8dbfbfd5-nk8gw | ERROR  |                                | …
```
=> Openstack: handle invalid server status while waiting

.ci/build, .ci/integration-tests, .ci/test, Makefile, docs/development/local_setup.md
For cmd/go the default behaviour in go modules is to look up the proper modules through the network. `-mod=vendor` prevents that and forces the use of `vendor/`.
Ref golang/go#27227
Fixes #
```improvement operator
NONE
```
=> Use -mod=vendor

pkg/controller/drain.go, pkg/controller/drain_test.go, pkg/controller/machine.go
Split drain force flag into two - forceDeletePods, ignorePodsWithoutControllers
Fixes #
```improvement operator
Bugfix: Allows force deletion of pods who have no controllers backing them
```
=> Bugfix: Allows force deletion of pods who have no controllers backing them (#300)

pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go, pkg/apis/machine/zz_generated.deepcopy.go, pkg/client/clientset/internalversion/fake/register.go, pkg/client/clientset/versioned/fake/register.go, pkg/client/clientset/versioned/scheme/register.go, pkg/client/informers/externalversions/machine/v1alpha1/alicloudmachineclass.go, pkg/client/informers/externalversions/machine/v1alpha1/awsmachineclass.go, pkg/client/informers/externalversions/machine/v1alpha1/azuremachineclass.go, pkg/client/informers/externalversions/machine/v1alpha1/gcpmachineclass.go, pkg/client/informers/externalversions/machine/v1alpha1/machine.go, pkg/client/informers/externalversions/machine/v1alpha1/machinedeployment.go, pkg/client/informers/externalversions/machine/v1alpha1/machineset.go, pkg/client/informers/externalversions/machine/v1alpha1/machinetemplate.go, pkg/client/informers/externalversions/machine/v1alpha1/openstackmachineclass.go, pkg/client/informers/externalversions/machine/v1alpha1/packetmachineclass.go, pkg/client/informers/internalversion/machine/internalversion/alicloudmachineclass.go, pkg/client/informers/internalversion/machine/internalversion/awsmachineclass.go, pkg/client/informers/internalversion/machine/internalversion/azuremachineclass.go, pkg/client/informers/internalversion/machine/internalversion/gcpmachineclass.go, pkg/client/informers/internalversion/machine/internalversion/machine.go, pkg/client/informers/internalversion/machine/internalversion/machinedeployment.go, pkg/client/informers/internalversion/machine/internalversion/machineset.go, pkg/client/informers/internalversion/machine/internalversion/machinetemplate.go, pkg/client/informers/internalversion/machine/internalversion/openstackmachineclass.go, pkg/client/informers/internalversion/machine/internalversion/packetmachineclass.go
Not sure if this is intended, but `hack/generate-code` on `master` regenerates all the types for me. Is this just my setup?
Environment:
```
go version go1.12.7 darwin/amd64
```
```improvement operator
NONE
```
=> Regenerated API Types because the latest Version is not checked in

pkg/controller/deployment_rollback.go
This reduces one extra error check when fetching MachineSet object.
=> Refactor error handling when fetching MachineSet object

pkg/apis/machine/types.go
Removed `+optional` from internal API types since it is not needed there.
```improvement operator
NONE
```
=> Removed optional annotation in internal types

pkg/controller/machine.go, pkg/controller/machine_test.go
Deletes node object once the machine object is deleted. This removes any hanging node objects in the cluster. 
Fixes #186 
```improvement user
Deletes nodes object on machine (object) deletion
```
=> Deletes nodes object on machine deletion

pkg/controller/alicloudmachineclass.go, pkg/controller/awsmachineclass.go, pkg/controller/azuremachineclass.go, pkg/controller/gcpmachineclass.go, pkg/controller/openstackmachineclass.go, pkg/controller/packetcloudmachineclass.go, pkg/controller/secret.go
**What this PR does / why we need it**:  This PR attempts to solve the reported issue of orphan MachienClasses/Secrets and MachineDeployments. 
MCM uses finalizers to make sure :
- MachineClass/Secrets are not deleted before referring MachineDeployments are deleted.
- MachineClasses/Secrets are removed timely after all the referring MachineDeployments are deleted.
We had observed the bug in both cases mentioned above, where sometimes Machineclasses/Secrets or Machinedeployments being orphaned/not-deleted while shoot-deletion.
Bug above has not been actively re-produced but certain observations below on healthy-clusters made the guesstimation of root-causes more clearer.
- Finalizer was found missing in few machine-classes in healthy clusters.
- In few cases restarting the MCM re-enqueued …
=> Bugfix: Improve the management of finalizers and re-enqueue-mechanism for MachineClasses and Secrets

kubernetes/Secrets/openstack-secret.yaml, pkg/apis/machine/v1alpha1/types.go, pkg/driver/driver_openstack.go
This PR adds the support for `userDomainID` as an authentication parameter.
Relates to #311 
```improvement operator
Added missing user_domain_id secret field for OpenStack driver
```
=> Added missing user_domain_id secret field

pkg/driver/driver_gcp.go
Additional user data on GCP is added by passing key/value pairs. The key is the name of the data and the value is the actual data itself.At the moment no matter what is the type of the data (cloud-config or script) we always set the key to be "user-data". But when GCP see such key it assumes that is dedicated to cloud-init binary so passing a script as a user-data and the corresponding binary is missing the script will to be ran. By making the MCM to differentiate between cloud-config and script now we can set the corresponding key to be either "user-data" or "startup-script". Thus the script will be executed on each boot after the network is up.
Fixes # …
=> makes MCM GCP driver to differentiate user-data from startup-script

kubernetes/machine_classes/azure-machine-class.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go, pkg/apis/machine/validation/azuremachineclass.go, pkg/apis/machine/zz_generated.deepcopy.go, pkg/driver/driver_azure.go, pkg/openapi/openapi_generated.go
Azure Machines can be deployed into a Zone OR an AvailabilitySet.
Both in parallel is not possible and will lead to an error.
To support zoned Azure Shoot clusters the MCM need to deploy and manage Azure machines in availability zones.
Fixes #332
```improvement user
MCM supports now Azure machines deployed into availability zones. You can either deploy a machine into a zone or an AvailabilitySet.
```
=> Add support for zoned Azure machines

.ci/integration-tests
The integration tests fail when freeze event isn't caught. This makes freeze checking more often during integration tests
Fixes #
```improvement operator
```
=> More frequent freeze checker during integration tests

.ci/integration-tests
The IT fails currently due to an older version of Kubectl being used.
Fixes #
```improvement operator
Updated Integration Tests kubectl to `v1.16.0`
```
=> Updated Kubectl to v1.16.0

Dockerfile, Makefile
This PR adds a multi stage build `Dockerfile` to this project and removes the necessity to run a local build prior to a `make docker-images` run.
```improvement developer
Added multi stage docker build
```
=> Added multi stage docker build

kubernetes/machine_classes/gcp-machine-class.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/driver/driver_gcp.go, pkg/openapi/openapi_generated.go
Fixes #339 
```noteworthy operator
⚠️ GCP VM's Public IP attachment is now optional. Default behaviour is that public IP attachment is enabled. To disable this, refer to [this example here](https://github.com/gardener/machine-controller-manager/blob/master/kubernetes/machine_classes/gcp-machine-class.yaml#L27)
```
=> GCP VM's Public IP attachment is now optional

cmd/machine-controller-manager/app/controllermanager.go, cmd/machine-controller-manager/app/options/options.go, go.mod, kubernetes/deployment/deployment.yaml, pkg/controller/controller.go, pkg/controller/machine.go, pkg/controller/machine_test.go, pkg/options/types.go
**What this PR does / why we need it**: This PR makes the node-conditions configurable, based on which machines are replaced.
Fixes #
```improvement operator
Node-conditions are configurable via flag. Users can provide the list of node-conditions based on which machines are replaced if set to true for health-timeout period.
```
=> Make node-conditions configurable

kubernetes/machine_classes/azure-machine-class.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/validation/azuremachineclass.go, pkg/driver/driver_azure.go, pkg/openapi/openapi_generated.go
As follow up on #326, remove deprecated fields.
Fixes #
```action user
Since version `0.22.0` the fields `Spec.Properties.StorageProfile.ImageReference.[Publisher|Offer|Sku|Version]` in the `AzureMachineClass have been deprecated and now they are completely removed. Please switch to `Spec.Properties.StorageProfile.ImageReference.URN` before upgrading to this version or higher.
```
=> Remove deprecated fields publisher,offer,sku,version

pkg/controller/machine.go, pkg/driver/driver_openstack.go
New logic ensures that the machine resources after the failed create process are purged. If there are no VMs, the `Delete()` method will return nil.
In addition in OpenStack environment, the `Delete()` method will wait until the machine resource is actually deleted, before creating a new machine. This can avoid quota limit exceptions.
Fixes #355 
```improvement operator
- improvement: OpenStack: Ensure VMs are deleted after unsuccessful create operation
```
=> OpenStack: Ensure VMs are deleted after unsuccessful create operation

pkg/apis/machine/install/install.go
The generated `pkg/client/clientset/internalversion/scheme/register.go`
https://github.com/gardener/machine-controller-manager/blob/f08fa09972caae2df8e407f2737645f085c9e7e6/pkg/client/clientset/internalversion/scheme/register.go#L5-L11
has import to package `pkg/apis/machine/install` which is currently missing. That's why the vendoring currently with go@1.13 fails.
g/g has this install.go - https://github.com/gardener/gardener/blob/0.31.2/pkg/apis/garden/install/install.go
k/sample-apiserver has this install.go - https://github.com/kubernetes/sample-apiserver/blob/kubernetes-1.16.3/pkg/apis/wardle/install/install.go
Ref #358 
```improvement operator
NONE
```
=> Add missing install pkg

pkg/driver/driver_alicloud.go
AliCloud Seed clusters uses CSI volume plugin. Need to consider it.
Fixes #
```improvement operator
When nodes are rolling updated, pods with Persistent volume attached can now be evicted correctly/serially before the node is drained.
```
=> Add csi volume fetching for AliCloud

pkg/controller/drain.go, pkg/controller/drain_test.go, pkg/controller/machine.go
**What this PR does / why we need it**: This PR further improves the drain logic by increasing PodEvictionRetryInterval to 20s and MaxEvictRetries till drain-timeout occurs.
- We have identified, PDBs could be violated if eviction retries are capped to a smaller value.
Partially solves:  [#1673](https://github.com/gardener/gardener/issues/1673)
**Special notes for your reviewer**: 
```improvement operator
Drain logic now attempts to evict the pod till drain-timeout has occurred. The interval between consecutive attempts to evict the pod has been increased to 20s.
```
=> Increase MaxEvictRetries and PodEvictionRetryInterval

cmd/machine-controller-manager/app/controllermanager.go, pkg/controller/controller.go
Currently, due to failed leader election (in the case of multiple machine-controller-managers), the liveness probe will constantly restart a container, which is confusing at best and may trip a monitoring system. Also, it makes no sense to not enable liveness probe immediately. Liveness probe should start to fail once a program transitions into a state, in which it won't be able to continue operating correctly, and it needs to be shut down externally.
```noteworthy operator
Healthz endpoint is immediately initialized with a healty (200) response
```
=> Activate healthz earlier

pkg/controller/drain.go, pkg/controller/machine.go, pkg/controller/machine_test.go
**What this PR does / why we need it**: This PR skips the force-deletion of the machine when the previous drain has failed.
Fixes #
```improvement operator
Avoided force-deleting the machine if previous drain has failed.
```
=> Avoid force-deleting if previous drain has failed

kubernetes/machine_classes/openstack-machine-class.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/validation/openstackmachineclass.go, pkg/driver/driver_openstack.go, pkg/openapi/openapi_generated.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/results.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/urls.go, vendor/modules.txt
This PR extends the OpenStack MachineClass to support custom root disk size. It does this by adding a Cinder based root disk volume to the VM created via MCM.
To configure the root disk size the manifest looks like the following
```shell
apiVersion: machine.sapcloud.io/v1alpha1
kind: OpenStackMachineClass
metadata:
name: test-openstack # Name of OpenStack machine class goes here
namespace: default # Namespace in which the machine class is to be deployed
spec:
...
rootDiskSize: 100 # 100 GB 
```
The creation policy for the Cinder volume is `DeleteOnTermination` meaning that the volume gets removed when the machine is terminated.
Fixes #386 
```improvement operator
Added Cinder based root disk …
```
=> Added Cinder based Custom Root Disks for OpenStack Vms

pkg/apis/machine/v1alpha1/types.go, pkg/openapi/openapi_generated.go
Fixes https://github.com/gardener/autoscaler/issues/20 
Machine-controller-manager is already working with zero replicas, but the status was not defined which means doing kubectl get machinedeployments will show blank. With the change it will set the replicas status to 0.
```improvement operator
Allow status to be defined when replicas is not defined or equal to 0.
- category:       improvement
- target_group:   user
```
=> Update status when replicas undefined or equal to zero

cmd/machine-controller-manager-cli/main.go, pkg/controller/machine.go, pkg/controller/machine_safety.go, pkg/controller/machine_test.go, pkg/driver/driver.go, pkg/driver/driver_alicloud.go, pkg/driver/driver_aws.go, pkg/driver/driver_azure.go, pkg/driver/driver_fake.go, pkg/driver/driver_gcp.go, pkg/driver/driver_openstack.go, pkg/driver/driver_packet.go, pkg/fakeclient/client.go
Fixes #382 
```improvement operator
Bugfix: Fixes race between machine & machineSet creation/deletion operations
```
=> Bugfix: Fixes race between machine & machineSet creation/deletion operations

pkg/driver/driver_aws.go
This PR fixes regressions from PR 379 where an error handling was wrongly handled causing orphan VMs. 
Fixes #
```improvement operator
```
=> Bugfix: Fixed regressions from PR-379

pkg/controller/machine.go
Don't requeue machine key if it not found
Fixes #402 
```improvement operator
Stops reconciling machine objects that no longer exists
```
=> Don't requeue machine key if error returned is "not found"

pkg/metrics/metrics.go, pkg/util/reflector/prometheus/prometheus.go, pkg/util/workqueue/prometheus/prometheus.go
Prepend MCM to all work queue metrics to make MCM metrics unique
Fixes #
```noteworthy operator
Prepend mcm to all work queue metrics
```
```noteworthy operator
Subsystems and Namespaces to MCM metrics
```
```noteworthy operator
Renamed mcm_machine_deployment_items_total & mcm_machine_set_items_total metrics
```
=> Prepend mcm to all work queue metrics

go.mod, go.sum, pkg/driver/driver_openstack.go, vendor/github.com/gophercloud/utils/client/client.go, vendor/github.com/gophercloud/utils/client/doc.go, vendor/github.com/gophercloud/utils/env/env.go, vendor/github.com/gophercloud/utils/env/env_windows.go, vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go, vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go, vendor/github.com/gophercloud/utils/openstack/clientconfig/results.go, vendor/github.com/gophercloud/utils/openstack/clientconfig/utils.go, vendor/k8s.io/klog/README.md, vendor/modules.txt
Setting the verbosity to 6 allows to print detailed OpenStack API requests/responses.
```improvement operator
Openstack: Print API request/response debug when verbosity is set to 6
```
cc @rfranzke . It might be an idea to introduce an interface to enable verbose logging dynamically, because if you change the manifest for one particular shoot, it will be reconciled with the defaults. Any thoughts on how to do this?
=> OpenStack: Print API request/response debug, when verbosity is set to 6

pkg/driver/driver_openstack.go
Currently, we have to contact an API to figure out the reason for a Server's ERROR status. Let's provide all the info in-band.
```improvement operator
When a Server creation ERRORs out in the openstack driver, provide formatted Fault information
```
=> [openstack] Provide Fault information when Server creation ERRORs out

kubernetes/deployment/target-cluster-role.yaml
Read access to PV is required when draining machines
so pods with PVs can be evicted sequentially
rather than in parallel for pods with no PVs.
Fixes #431
=> Add missing rbac roles to controller manager

pkg/controller/controller_suite_test.go, pkg/controller/controller_utils.go, pkg/controller/controller_utils_test.go
Fixes #422 
```improvement operator
Sort active machines by creation timestamp
```
=> Sort active machines by creation timestamp

kubernetes/machine_classes/azure-machine-class.yaml, pkg/apis/machine/validation/azuremachineclass.go, pkg/driver/driver_azure.go
Support VM Image ID for Azure.
With this change VMs can be created not only from URN, but also from image ID.
This is necessary when the VM images are not available in the marketplace and URN cannot be used. 
Fixes #
```improvement operator
Azure VMs now can be created with image ID.
```
=> Support VM Image ID for Azure

pkg/controller/machine.go, pkg/controller/machine_test.go, pkg/driver/driver.go, pkg/driver/driver_azure.go, pkg/driver/driver_fake.go
**What this PR does / why we need it**: This PR addresses the cases when an unfortunate restart of the MCM can make it lose the state. MCM now lists the VMs in the cloud, before actually creating or deleting the machines. 
- This PR also enables MCM to adopt the dynamically node-object in case it is not populated on the machine-object while creation. 
Fixes #423 
```improvement operator
Improves the machine-creation and machine-deletion flow by listing and verifying the state of the machines before actual creation and deletion. 
```
```improvement operator
MCM now dynamically maps the node-objects with machines if `Status.Node` is not set. 
```
=> Improve machine creation and deletion flow by listing the machines before actual creation/deletion

cmd/machine-controller-manager/app/controllermanager.go, cmd/machine-controller-manager/app/options/options.go, pkg/controller/controller.go, pkg/controller/machine_bootstrap_token.go, pkg/options/types.go
I'd like to access Kubernetes objects in some way or another using the bootstrap token. It's possible to do just that by providing the [`auth-extra-groups`](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/#bootstrap-token-secret-format) field (this PR) and creating a Role/RoleBinding. 
The format of the configuration is open to discussion. Perhaps, it would be better to move this to a per-MachineClass Secret?
```improvement user
Provide a way to specify "auth-extra-groups" field in created bootstrap tokens.
```
=> Add "auth-extra-groups" field to bootstrap token

pkg/controller/machine.go, pkg/controller/machine_test.go
Do not adopt Nodes with an empty ProviderID field.
We've hit a nasty cloud-controller-manager bug: manually created master Node has not been assigned a ProviderID. As a result, the machine-controller-manager adopted the master Node, promptly replacing its metadata and removing it after when Machine has been removed.
```improvement operator
The mcm stopped adopting Nodes with empty ProviderID field
```
=> Do not adopt Nodes with empty ProviderID field

pkg/controller/drain.go, pkg/controller/machine.go, pkg/controller/machine_test.go
Sometimes (mainly due to incorrect requests/limits in our case) a Node's kubelet might become unavailable. Let's skip drain completely on these Nodes.
Fixes #448 
[This](https://dev.to/duske/how-kubernetes-handles-offline-nodes-53b5) article is of use while trying to understand Node NotReady status. I've come to the conclusion that checking current Node Conditions should be enough,
```operator user
The drain is completely skipped if the node is NotReady for the timeout period. Default timeout is 5 mins. 
```
=> Skip drain on NotReady Nodes

pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go, pkg/apis/machine/zz_generated.deepcopy.go, pkg/driver/driver_aws.go, pkg/openapi/openapi_generated.go
**What this PR does / why we need it**: Enable support of snapshot-based volumes for machines in AWS.
Fixes #
```improvement operator
Enable support of snapshot-based volumes for machines in AWS.
```
=> Add SnapshotID field in AWSMachineClass

kubernetes/machine_classes/aws-machine-class.yaml
**What this PR does / why we need it**: Fixes the typo in aws-machine-class. 
Check: https://github.com/gardener/machine-controller-manager/blob/master/pkg/apis/machine/v1alpha1/types.go#L804
Fixes #
```improvement operator
```
=> Fix typo in AWSMachineClass

pkg/driver/driver_azure.go
fixes regression when using VM image resource id / an image from a shared image gallery
Fixes #474 
```improvement operator
Azure: Fixes regression when using a VM image resource id instead of an URN (for example an image from a shared image gallery)
```
=> fix vm creation when using image id

pkg/controller/machine.go, pkg/controller/machine_test.go, pkg/util/provider/machinecontroller/controller_suite_test.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go
Fixes #465 
```improvement developer
Bugfix: Drain machines with only a valid node (name)
```
=> Bugfix: Drain machines with only a valid NodeName

kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/openstack_machineclass_types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go, pkg/apis/machine/zz_generated.deepcopy.go, pkg/driver/driver_openstack.go, pkg/openapi/openapi_generated.go
Add an option to use config drive while provisioning OpenStack Servers.
```improvement operator
Added an option to use configDrive in the OpenStackMachineClass
```
=> [openstack] Config drive option

kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml, pkg/controller/deployment_machineset_util.go
https://github.com/gardener/machine-controller-manager/pull/471
Fixes regressions caused by [PR #471](https://github.com/gardener/machine-controller-manager/pull/471)
With k8s version 1.18 `metadata.description` isn't supported. And also there was a bug while trying to create a machineSet with a null value for `newstatus.LastOperation.LastUpdateTime` which can no longer be null due to validation. 
```
E0730 17:15:56.773686   16403 machineset.go:535] Update machineSet test-machine-deployment-7dbb854886 failed with: MachineSet.machine.sapcloud.io "test-machine-deployment-7dbb854886" is invalid: status.lastOperation.lastUpdateTime: Invalid value: "null": status.lastOperation.lastUpdateTime in body must be of type …
```
=> Fixes regressions caused by PR #471

pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/aws_machineclass_types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go, pkg/apis/machine/zz_generated.deepcopy.go, pkg/driver/driver_aws.go, pkg/openapi/openapi_generated.go
This takes care of the AWS Spot Instances support part of the #27.
AWS part of #27
```noteworthy user
Support for Spot Instances is available in AWS driver. If the `spotPrice` is empty, price is automatically set to the on-demand price so that Spot instance can launch immediately.
```
=> [aws] Spot Instances support

pkg/controller/controller_suite_test.go, pkg/controller/machine.go, pkg/controller/machine_test.go
The PR returns an `error` when the Secret referred by the MachineClass is absent/not created yet. Waits until the secret is created while prompting it on the logs. MachineDeployment immediately reconciles when the referred secret is available later.
Fixes #430 
This is my first PR to this repo. I have tried my best to adhere to the guidelines. Let me know if there is anything to be rectified.
```improvement user
Retry when secret is referred by machineClass is missing
```
@hardikdr @prashanth26
=> Retry when secret is referred by machineClass is missing

kubernetes/deployment/in-tree/control-cluster-role.yaml, kubernetes/deployment/out-of-tree/control-cluster-role.yaml, pkg/controller/controller_utils.go, pkg/controller/machine.go, pkg/controller/machine_util.go, pkg/controller/machine_util_test.go, pkg/util/conditions/conditions.go
Helps users monitor and react to ongoing node terminations.
Fixes #488
Assumes that termination is final in MCM, and a terminating node cannot be restored. So, only situations where the termination condition is true are handled. 
Note that some RBAC changes are required to allow MCM updates of the node's status. 
```noteworthy operator
RBAC policies have to be updated to allow updating of `node/status` resources. 
```
```improvement user
Node condition is added to the status of terminating nodes indicating the termination start time and reason (Unhealthy|ScaleDown)
```
=> Add termination condition to deleting nodes

pkg/controller/deployment_sync.go
Currently, MachineSet names are with variable length of the random hash. The MCM is also not limiting the random hash in the machineset names. But if we limit the length of the random hash, it will help to reduce the occurrences of the CSI issue till it is fixed upstream
Fixes #461 
```improvement operator
NONE
```
=> Limit the Random Hash in the MachineSet Name

cmd/machine-controller-manager/app/controllermanager.go, cmd/machine-controller-manager/app/options/options.go, pkg/controller/controller.go, pkg/controller/controller_utils.go, pkg/controller/controller_utils_test.go, pkg/controller/deployment_recreate.go, pkg/controller/deployment_rolling.go, pkg/controller/deployment_rolling_test.go, pkg/controller/deployment_util.go, pkg/options/types.go, pkg/util/annotations/annotations.go, pkg/util/annotations/annotations_suite_test.go, pkg/util/annotations/annotations_test.go, pkg/util/taints/taints.go
**What this PR does / why we need it**: With this PR, during roll out of the machine-deployment, all the machines under it are annotated with `cluster-autoscaler.kubernetes.io/scale-down-disabled: "True"`. 
This will help us keeping the cluster-autoscaler running even during the cluster-rollouts. CA will not scale-down a specific machine-deployment which is being rolled, but will be able to scale-down the rest of them. Also, CA will be able to scale-up all the machine-deployments during roll-outs.
There are mainly 2 parts to the PR:
1. Adding the annotation during roll-out.
- To determine if the roll-out if on-going we check if there are old-machine-sets that are not scaled-to-zero completely. We check the `up-to-date`, and `ready` replicas as well here.
2. Removing the annotation after …
=> Inhibit scale-down by autoscaler during roll-outs.

pkg/driver/driver_alicloud.go, pkg/driver/driver_aws.go, pkg/driver/driver_aws_test.go, pkg/driver/driver_azure.go, pkg/driver/driver_azure_test.go, pkg/driver/driver_gcp.go, pkg/driver/driver_gcp_test.go, pkg/driver/driver_openstack.go, pkg/driver/driver_openstack_test.go, pkg/util/provider/machinecontroller/controller.go, pkg/util/provider/machinecontroller/machine_test.go
Wait also for CSI PVs during serial eviction.
/kind bug
Fixes #508
```improvement operator
An issue causing machine-controller-manager to not consider CSI PersistentVolumes during the eviction of Pods with PersistentVolumes is now fixed.
```
=> Wait also for CSI PVs during serial eviction

kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml, kubernetes/machine_classes/openstack-machine-class.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/openstack_machineclass_types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go, pkg/apis/machine/zz_generated.deepcopy.go, pkg/driver/driver_openstack.go, pkg/openapi/openapi_generated.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/requests.go, vendor/modules.txt
Adds an extra optional field for specifying the ServerGroup in a machineClass. The PR is a preparation for managing workergroup anti-affinity via ServerGroups. ServerGroup creation and management will be implemented on the Openstack-extension side.
Fixes #30 
```improvement operator
Add support for ServerGroups in the Openstack driver. VMs can now be created in the ServerGroup specified in the respective `MachineClass`.
```
=> ServerGroup option for Openstack MachineClass

pkg/driver/driver_aws.go
Allow deletion of VMs even on list image or modify instance failure
Fixes #514 
```improvement operator
AWS: Allow deletion of VMs even on list image or modify instance failure
```
=> AWS: Allow deletion of VMs even on list image or modify instance failure

pkg/driver/driver_aws.go
Allow deletion of VM even on image/instance get failures.
Fixes #520 
```noteworthy user
Allow deletion of VM even on image/instance get failures.
```
=> Allow deletion of VM even on image/instance get failures.

pkg/driver/driver_azure.go
Tag verification has been [disabled](https://github.com/gardener/machine-controller-manager/commit/8e5e2568b9f7abd8f8f8769704ade2bd5051873e) back in May of 2019 by @prashanth26.
We can deduce that it was done due to Azure's unique ability to group resources in Resource Groups. Gardener project, presumably, packs all VMs (and relevant objects) into a single Resource Group (hence no need for tag verification).
That does not work for us, since we deploy master VMs near VMs that are managed by MCM and backed by Machine objects. It also seems weird that there are tags present in AzureMachineClass CRD, but are not used to verify actual objects.
```improvement user
Restored tag verification in the …
```
=> [azure] Verify tags

pkg/driver/driver_aws.go
Allows deletion of machines even on modify instance call failure
Fixes #514 
```noteworthy user
AWS: Allows deletion of machines even on modify instance call failure
```
=> Allow deletion of machines where modify instance fails on deletion

pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/machine_types.go, pkg/controller/controller_utils.go, pkg/controller/deployment_machineset_util.go, pkg/controller/machine.go, pkg/controller/machine_test.go, pkg/controller/metrics.go
Co-authored-by: Prashanth <prashanth@sap.com>
**What this PR does / why we need it**:  Currently we immediately re-enqueue the machine-object on creation/deletion failure. This PR adds a constant delay before retrying the operation. Eventually, we must build exponential retry on top or parallel to this solution. 
- PR introduces a new phase `CrashLoopBackOff`. This should be used when machine creation fails, but machine-set doesn't really need to replace the machine-object[as that won't anyways help]. 
Fixes #
```noteworthy operator
Introduce a delay in re-enqueuing machines during creation/deletion failures. 
```
```improvement developer
Adds a new phase `CrashLoopBackOff` that is set due to machine …
```
=> Cherry-pick on master: Introduce delay in re-enqueuing machines during creation-deletion failures.

pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/machine_types.go, pkg/controller/controller_utils.go, pkg/controller/deployment_machineset_util.go, pkg/controller/machine.go, pkg/controller/machine_test.go, pkg/controller/metrics.go
Co-authored-by: Prashanth <prashanth@sap.com>
**What this PR does / why we need it**:  Currently we immediately re-enqueue the machine-object on creation/deletion failure. This PR adds a constant delay before retrying the operation. Eventually, we must build exponential retry on top or parallel to this solution. 
- PR introduces a new phase `CrashLoopBackOff`. This should be used when machine creation fails, but machine-set doesn't really need to replace the machine-object[as that won't anyways help]. 
Fixes #
```noteworthy operator
Introduce a backoff in re-enqueuing machines on creation/deletion failures. Avoids throttling APIServer & provider calls.
```
```improvement developer
Adds a new phase …
```
=> Introduce delay in re-enqueuing machines during creation--deletion failures.

pkg/controller/alicloudmachineclass.go, pkg/controller/awsmachineclass.go, pkg/controller/azuremachineclass.go, pkg/controller/controller.go, pkg/controller/gcpmachineclass.go, pkg/controller/openstackmachineclass.go, pkg/controller/packetcloudmachineclass.go, pkg/util/provider/machinecontroller/controller.go, pkg/util/provider/machinecontroller/machineclass.go, pkg/util/provider/machinecontroller/machineclass_test.go
Without proper finalizers, machine classes backing machines were lost on deletions. 
Fixes #
This partially reverts this change - https://github.com/gardener/machine-controller-manager/commit/0a568917461a5c6385974322784b36d62762e60a#diff-a327d9bce2e5949213510b45b329fa9d45d2dedfcce11e407e51e876549f265bL130-L137
```improvement operator
Added a more comprehensive set of events to trigger machine class reconciliations.
```
```improvement operator
Finalizers are added by default for all machine class objects.
```
=> Bugfix: Fixed issues with machineClass finalizers 

pkg/controller/alicloudmachineclass.go, pkg/controller/awsmachineclass.go, pkg/controller/azuremachineclass.go, pkg/controller/controller.go, pkg/controller/gcpmachineclass.go, pkg/controller/openstackmachineclass.go, pkg/controller/packetcloudmachineclass.go, pkg/util/provider/machinecontroller/controller.go, pkg/util/provider/machinecontroller/machineclass.go, pkg/util/provider/machinecontroller/machineclass_test.go
Without proper finalizers, machine classes backing machines were lost on deletions. 
This partially reverts this change - https://github.com/gardener/machine-controller-manager/commit/0a568917461a5c6385974322784b36d62762e60a#diff-a327d9bce2e5949213510b45b329fa9d45d2dedfcce11e407e51e876549f265bL130-L137
```improvement operator
Added a more comprehensive set of events to trigger machine class reconciliations.
```
```improvement operator
Finalizers are added by default for all machine class objects.
```
=> Bugfix: Fixed issues with machineClass finalizers (rel-v0.34.0)

docs/development/cp_support_new.md
The documentation was pointing to the wrong branch. This change fixes it.
Fixes #
```improvement operator
NONE
```
=> Fix typo in documentation

cmd/machine-controller-manager/app/options/options.go, kubernetes/deployment/in-tree/deployment.yaml, kubernetes/deployment/out-of-tree/deployment.yaml, kubernetes/machine_objects/machine-deployment.yaml, pkg/controller/machine_test.go, pkg/util/provider/app/options/options.go, pkg/util/provider/machinecontroller/machine_test.go
Machine-controller-manager should also check for the NetworkUnavailable nodeCondition, some CNI will update this condition depending on the state of the CNI or the network availability.
Fixes #https://github.com/gardener/machine-controller-manager/issues/469
```improvement operator
NetworkUnavailable nodeCondition added to the example, some CNI will update this condition depending on the state of the CNI or the network availability.
```
=> Add NetworkUnavailable as node condition

docs/FAQ.md
**What this PR does / why we need it**: ToC links in the "Basics" section of FAQ were broken due to excessive spaces in titles.
Fixes #
```improvement operator
```
=> Removing excessive spaces in FAQ

pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machinecontroller/machine_util.go
The OOT implementation reverted the logic that was required to track time between drain retries. This PR fixes it. Refer previous code here - https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/machine.go#L741.
Fixes #547 
The PR also contains minor nits. 
```improvement operator
OOT: Fixes drain timeout issues on retires
```
=> OOT: Fixes drain timeout issues on retires

kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/openstack_machineclass_types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go, pkg/apis/machine/zz_generated.deepcopy.go, pkg/driver/driver_openstack.go, pkg/openapi/openapi_generated.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/urls.go, vendor/modules.txt
Adds the ability to specify an already existing OpenStack Neutron network in the subnetID of an OpenStackMachineClass. MCM will deploy new machines into the given subnet by pre-allocating Neutron ports and pass them to the Nova server object. Pre-allocated ports will be specifically removed upon server termination. This is required to specify an existing subnet in a shoot manifest. 
With this PR it is only possible to specify an already existing network, not a list of otherwise pre-allocated ports.
Partly fixes #535 
This change is a necessary precondition for [PR 169](https://github.com/gardener/gardener-extension-provider-openstack/pull/169) in …
=> Deploy VMs into existing OpenStack Neutron network

docs/development/cp_support_new.md, kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml
**What this PR does / why we need it**:  Fix the OpenAPI validation of the machine-deployment crd
Related to: https://github.com/kubernetes/kubernetes/issues/80493
Fixes #
```improvement operator
Fix the OpenAPI validation of the machine-deployment crd
```
=> Fix the OpenAPI validation of the machine-deployment crd

pkg/controller/drain.go, pkg/util/provider/drain/drain.go, pkg/util/provider/machinecontroller/controller_suite_test.go, pkg/util/provider/machinecontroller/machine_util.go
- The maxEvictRetries parameter was being computed wrongly with the OOT leading to longer (12hours) drain timeouts. Now this value is computed as it is with in-tree. Refer -[in-tree code]( https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/machine.go#L629). 
- The default drainTimeout value has been updated from 12hours to 2hours. 
Fixes https://github.com/gardener/machine-controller-manager-provider-gcp/issues/9
I have tested this PR and is in line with the in-tree implementation now. 
```improvement user
The default drainTimeout value has been updated from 12hours to 2hours. 
```
```improvement user
OOT: Fixed regression with …
```
=> Fixed regression (OOT) with maxEvictRetries and defaulted drain timeout to 2hours

.ci/integration-tests
**What this PR does / why we need it**: Adapts the integration test script to fail if there are any leftover orphan resources after the tests.
Fixes #498 
```improvement operator
Adapted integration tests to handle possibly orphaned resources.
```
=> Adapt integration tests to handle possibly orphaned resources

pkg/controller/machine.go
**What this PR does / why we need it**:  MCM uses the cache-based listers instead of direct client calls while machine-reconciliation. 
Fixes #536 
```improvement operator
Use cache-based listers to GET the machine-object while reconciling.
```
=> Use listers to get the machine-object during reconciliation

pkg/controller/machine.go, pkg/util/provider/machinecontroller/controller_suite_test.go, pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machinecontroller/machine_safety.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go, pkg/util/provider/machinecontroller/machine_util_test.go, pkg/util/provider/machinecontroller/migrate_machineclass.go, pkg/util/provider/machinecontroller/migrate_machineclass_test.go, pkg/util/provider/machineutils/utils.go, pkg/util/strings/string.go
- Changes carried over from in-tree fix - https://github.com/gardener/machine-controller-manager/pull/525/
- Also removes the unused node object - https://github.com/gardener/machine-controller-manager/pull/525/files#diff-d52f3782153512c736878e861c6cafd75dd23f214af3f017eea14de256da458bR274-R278
Fixes #
```noteworthy operator
OOT: Introduced a backoff in re-enqueuing machines on creation/deletion failures. Avoids throttling APIServer & provider calls.
```
```improvement operator
OOT: Enqueue machine only when node conditions have changed.
```
/kind regression
/size l
=> OOT: Introduce backoff in re-enqueuing machines during creation/deletion failures

pkg/controller/controller_suite_test.go, pkg/controller/machine.go, pkg/util/provider/machinecontroller/controller_suite_test.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go, pkg/util/time/time.go, pkg/util/time/time_suite_test.go, pkg/util/time/time_test.go
This PR fixes the race condition that triggers force deletion of machines which are less than drain timeout minutes old. Fixes regressions from #492 . 
Fixes #563 
```improvement operator
Set Machine Phase to Terminating before draining. 
```
```noteworthy operator
Machine force deletion computation is based on deletionTimestamp instead of LastUpdatedTimestamp. 
```
/invite @guydaichs
=> Set Machine Phase to Terminating & make drain calculations based on deletionTimestamp

pkg/controller/controller_suite_test.go, pkg/controller/machine.go, pkg/util/provider/machinecontroller/controller_suite_test.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go, pkg/util/time/time.go, pkg/util/time/time_suite_test.go, pkg/util/time/time_test.go
…eletionTimestamp (#564)
* Fixes issues with machines being force drained
The machines were being force drained during race conditions due to PR #492.
This commit fixes that by
- Make the drain calculation based on deletion timestamp
- Reverted logic from PR #492 to first set machine Termination phase
* Update pkg/util/time/time_test.go
Fixed typo
Co-authored-by: Hardik Dodiya <hardik.dodiya@sap.com>
Fixes #
```improvement operator
Set Machine Phase to Terminating before draining. 
```
```noteworthy operator
Machine force deletion computation is based on deletionTimestamp instead of LastUpdatedTimestamp. 
```
=> Cherrypick PR#564 to v0.35

Dockerfile, pkg/controller/controller_suite_test.go, pkg/controller/machine.go, pkg/util/provider/machinecontroller/controller_suite_test.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go, pkg/util/time/time.go, pkg/util/time/time_suite_test.go, pkg/util/time/time_test.go
…eletionTimestamp (#564)
* Fixes issues with machines being force drained
The machines were being force drained during race conditions due to PR #492.
This commit fixes that by
- Make the drain calculation based on deletion timestamp
- Reverted logic from PR #492 to first set machine Termination phase
* Update pkg/util/time/time_test.go
Fixed typo
Co-authored-by: Hardik Dodiya <hardik.dodiya@sap.com>
Fixes #
```improvement operator
Set Machine Phase to Terminating before draining. 
```
```noteworthy operator
Machine force deletion computation is based on deletionTimestamp instead of LastUpdatedTimestamp. 
```
=> Cherrypick PR#564 to v0.34

Dockerfile
This PR uses the latest gcr copy for docker images. Fixes any rate-limiting issues while building images. 
Fixes #
```improvement operator
```
=> Update docker images to use latest gcr copy

Dockerfile
- Updated from golang:1.13.5 to eu.gcr.io/gardener-project/3rd/golang:1.15.5
- Updated from alpine:3.11.2 to eu.gcr.io/gardener-project/3rd/alpine:3.12.1
Fixes #
```improvement developer
Update docker images to use gcr copy
```
```improvement developer
Update docker image versions to `golang:1.15.5` & `alpine:3.12.1`
```
=> Update docker images to use gcr copy

docs/FAQ.md
**What this PR does / why we need it**: Added an faq for a `paused` field in machine-deployment.
Fixes #
```improvement operator
```
=> Add FAQ for paused field

pkg/driver/driver_azure.go
Allow MCM to delete Azure machines even if the underlying resource groups are already deleted. E. g. user delete the resource group manually.
Fixes #562
```improvement operator
MCM will delete Azure machines even if the underlying resource group is already deleted.
```
/invite @kon-angelo @ialidzhikov
=> Fix Azure machine deletion if resource group is gone

pkg/controller/deployment_sync.go
https://github.com/gardener/machine-controller-manager/pull/500 introduces a change that takes only the first 5 elements of the encoded machine template hash. This actually panics when the endoded machine template hash length is less than 5:
```
E1125 13:35:08.062639       1 runtime.go:78] Observed a panic: runtime.boundsError{x:5, y:4, signed:true, code:0x1} (runtime error: slice bounds out of range [:5] with length 4)
goroutine 713 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x212ff20, 0xc0007ee480)
/go/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) …
```
=> Prevent panic when machine template hash length is < 5

pkg/controller/deployment_sync.go
Signed-off-by: ialidzhikov <i.alidjikov@gmail.com>
#500 introduces a change that takes only the first 5 elements of the encoded machine template hash. This actually panics when the endoded machine template hash length is less than 5
Fixes #461 
Hotfix for a bug introduced by #500 
```improvement operator
None
```
=> Cherrypick PR#575 into MCM rel-v0.35 

pkg/controller/machine.go
This PR corrects the variable substitution with the corresponding format specifier in the log message
Fixes #
I found it while I was reading the code to understand working of MCM.
```other operator
NONE
```
=> Correcting the variable substitution

.docforge/manifest.yaml
**How to categorize this PR?**
/area documentation
/priority normal
Declares machine-controller-manager as documentation component and makes it discoverable for the tools building documentation e.g. for gardener.cloud
Fixes #586 
```
NONE
```
=> docforge manifest

pkg/controller/machine_safety.go, pkg/controller/machine_safety_test.go, pkg/controller/machine_test.go, pkg/driver/driver.go, pkg/driver/driver_fake.go, pkg/util/provider/driver/fake.go, pkg/util/provider/machinecontroller/machine_safety.go, pkg/util/provider/machinecontroller/machine_safety_test.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machineclass_test.go, pkg/util/provider/machinecontroller/migrate_machineclass_test.go
This PR will avoid the deletion of the machines in CrashLoopBackoff state by the safety controller
Fixes #583 
More UTs shall be added to test this scenario in the near future. This one is an immediate solution to mitigate the issue.
```other operator
Avoid the deletion of the machines in CrashLoopBackoff state by the safety controller
```
=> Avoid the deletion of the machines in CrashLoopBackoff state by the safety controller

.ci/integration-tests
Minor fix to update docker image before fetching and installing new libraries on CI pipeline runs
Fixes #
Without this command, the new cc job image is facing issues while running CI tests and failing with the following errors. 
```
.ci/integration-tests: line 98: jq: command not found
.ci/integration-tests: line 99: jq: command not found
```
```other operator
NONE
```
=> Run update before fetching on CI image

go.mod, go.sum, pkg/driver/driver_azure.go, pkg/util/backoff/backoff_suite_test.go, pkg/util/backoff/wait.go, pkg/util/backoff/wait_test.go, vendor/github.com/cenkalti/backoff/v4/.gitignore, vendor/github.com/cenkalti/backoff/v4/.travis.yml, vendor/github.com/cenkalti/backoff/v4/LICENSE, vendor/github.com/cenkalti/backoff/v4/README.md, vendor/github.com/cenkalti/backoff/v4/backoff.go, vendor/github.com/cenkalti/backoff/v4/context.go, vendor/github.com/cenkalti/backoff/v4/exponential.go, vendor/github.com/cenkalti/backoff/v4/go.mod, vendor/github.com/cenkalti/backoff/v4/retry.go, vendor/github.com/cenkalti/backoff/v4/ticker.go, vendor/github.com/cenkalti/backoff/v4/timer.go, vendor/github.com/cenkalti/backoff/v4/tries.go, vendor/modules.txt
- NIC creation now adopts any existing NICs with matching names
- NIC deletion confirms deletion by performing GET on the deletion
- Improved creation logs to give more details
Fixes https://github.com/gardener/machine-controller-manager/issues/544
```other operator
Improved NIC creation and deletion logic to handle NIC creation and deletions more gracefully.
```
=> Improved NIC creation and deletion logic

pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go
this PR provides the logic for skipping draining of nodes which are Ready and whose `ReadonlyFilesystem` condition is also true
Fixes #579 
```feature user
Skip node drain on ReadOnlyFileSystem condition
```
=> Skip node drain on readOnlyFileSystem condition

pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machinecontroller/machine_safety.go, pkg/util/provider/machinecontroller/machine_util.go
print logic for nodeName and providerID with machineName at key places added
this PR prints nodeName and provider-ID also ,with machineName so that it eases debugging
Fixes #606 
I have made changes only for `Info` logs not for `error` logs
```feature operator
Improved log details to include node name and provider-ID in addition to existing machine name
```
=> Improved log details to include node name and provider ID

pkg/controller/machine_util.go
It would assign nil to secretRef, and this would panic when trying
to log out the original namespace/name.
```bugfix operator
Fix panic when machineClass `secretRef` isn't found.
```
=> Fix panic when secretRef cannot be found

.gitignore, pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machinecontroller/machine_test.go
Adds on finalizers on machines that are adopted by MCM. Without this change, it causes issues while migrating machine objects between clusters. 
Fixes #610 
- This PR basically allows adding of finalizer when when backing VM is created and status is present on it.
- I have removed the test case as it no longer makes sense in that method. We should add a test suit to the main reconcile loop in the future.
```bugfix developer
Adds finalizers on machines that are adopted by the machine controller. Without this change, it causes issues while migrating machine objects between clusters. 
```
/assign @AxiomSamarth 
cc: @plkokanov
=> Adds finalizers on machines that are adopted by the machine controller

pkg/util/provider/machinecontroller/controller_suite_test.go, pkg/util/provider/machinecontroller/machine_test.go
- test framework for package `controller`  modified
- secrets now part of controlCoreObjects
- controlCoreClient used for fetching secrets
Fixes # 616
```bugfix developer
Fetches secrets from the correct (control) APIServer while running tests. 
```
=> Secrets moved to controlCoreObjects in tests

kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml, pkg/util/provider/machinecontroller/controller_suite_test.go, pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go, pkg/util/provider/machinecontroller/machineclass.go, pkg/util/provider/machinecontroller/machineclass_test.go
Implements MachineClasses to have finalizers only when machines backing them are present.
Fixes #560 
The change has been introduced for OOT MCM common library. If there is a need then it shall be introduced in In-Tree too.
```feature operator
Finalizers will be added to the MachineClass which is used by at least one machine. Machines whose backing MachineClass does not have finalizers shall not be reconciled.
```
=> Machines are reconciled only when MachineClasses have valid finalizers

.ci/integration-tests, pkg/controller/machine_safety_test.go, pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machinecontroller/machine_safety.go
This PR replaces an integration test with a unit test that tests the functionality of adding a freeze label on the MachineSet when there is overshooting
Fixes #619 
I have only commented out the unwanted integration test in this PR. Once, it is merged and we know for sure that this works fine, in the subsequent PRs of K8s vendoring I will have it removed from the code.
```feature developer
Replace integration test with unit test to test the functionality to freeze MachineSet
```
=> Replace integration test with unit test to test the functionality to freeze MachineSet

pkg/util/provider/machinecontroller/machineclass.go
This PR removes an unwanted residue log from `machineclass.go` 
Fixes #
```other operator
NONE
```
=> Removed an unwanted log

pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machinecontroller/machine_safety.go, pkg/util/provider/machinecontroller/machine_safety_test.go, pkg/util/provider/machinecontroller/machine_safety_util.go, pkg/util/provider/machinecontroller/machine_util.go, pkg/util/provider/machinecontroller/machineclass.go
Fixes regressions from https://github.com/gardener/machine-controller-manager/pull/593 and https://github.com/gardener/machine-controller-manager/pull/612. 
Fixes #625 
- MachineClass finalizer error to retry sooner 
- Enqueue machines on MC finalizer addition
- Annotate NotManagedByMCM only post creationTimeout
```other operator
None
```
/invite @himanshu-kun @AxiomSamarth
=> Fixes regressions from PR#593 and PR#612 

.ci/integration-tests
This PR is experimental to test if the race condition really occurs during rapid scale up and scale down. The overshooting period has been modified to 2s to checkout the scenario. 
Fixes #
If this integration tests pass then we are good with replacing the integration tests with UT. Otherwise, we may have to check and fix the possible occurrence of the race condition between MachineSet Controller and MachineSafetyController.
```other developer
NONE
```
=> Restore integration test along with UTs 

pkg/controller/deployment_rolling.go, pkg/controller/deployment_util.go, pkg/util/nodeops/taints.go, pkg/util/provider/drain/drain.go, pkg/util/provider/drain/volume_attachment.go, pkg/util/provider/machinecontroller/machine.go
- Machine rollouts are now more as desired with the number of replicas always maintained to `desired + maxSurge`. Earlier machines in termination were left out of this calculation but now is considered.
- Avoids blocking of drain call when the buffer is full for the `volumeAttachmentHandlers`. 
- `volumeAttachmentHandlers` are always closed now even on failure cases. 
Fixes #
```feature user
Machine rollouts are now more as desired with the number of replicas always maintained to `desired + maxSurge`. Earlier machines in termination were left out of this calculation but now is considered with this change.
```
```bugfix operator
Avoids blocking of drain call when …
```
=> Allow controlled machine drain and rollout

pkg/util/provider/machinecontroller/machine_util.go
This PR will propagate the error message from the providers onto the dashboard properly
Fixes [#33](https://github.com/gardener/machine-controller-manager-provider-azure/issues/33)
The PR is yet to be tested against a cluster
```other operator
NONE
```
=> fix to propagate the error on to the dashboard

docs/FAQ.md
The existing doc said that the label `force-deletion: "True"` should be applied when the machine object was already in deletion.
However it only works if the label is present when invoking `kubectl delete machine xxx`.
Fixes #
```other operator
```
=> Clarify when to apply the force deletion label

pkg/util/provider/app/options/options.go
Increase concurrent object syncs to 50 to allow concurrent object reconciles especially in cases such as machine drains to allow more parallel drains. 
Fixes #
Similar to https://github.com/gardener/machine-controller-manager/pull/491. 
```feature user
Increase default concurrent object syncs to 50 to allow more concurrent reconciles to occur.
```
/invite @amshuman-kr @AxiomSamarth
=> Increasing concurrent object syncs to 50

.ci/pipeline_definitions
This PR upgrades Go version in the CI pipeline to use v1.16.6
Fixes #
```other developer
NONE
```
=> Update go version on pipeline

kubernetes/crds/machine.sapcloud.io_alicloudmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_awsmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_azuremachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_gcpmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_machineclasses.yaml, kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml, kubernetes/crds/machine.sapcloud.io_machines.yaml, kubernetes/crds/machine.sapcloud.io_machinesets.yaml, kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_packetmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_scales.yaml, pkg/test/integration/common/framework.go
This PR:
Fixes #636 
```other developer
NONE
```
=> It suite improvements

Makefile, kubernetes/crds/machine.sapcloud.io_alicloudmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_awsmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_azuremachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_gcpmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_machineclasses.yaml, kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml, kubernetes/crds/machine.sapcloud.io_machines.yaml, kubernetes/crds/machine.sapcloud.io_machinesets.yaml, kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_packetmachineclasses.yaml, pkg/openapi/openapi_generated.go
This PR updates the version of `controller-gen` in MakeFile , which is used to generate crd.
With use of this , now we can generate v1 version of CRD using the rule `make generate`. Earlier v1beta1 was getting generated.
Fixes #
```doc developer
`make generate` now generates v1 version of CRDs by default instead of v1beta1.
```
=> using controller-gen latest version for crd generation

kubernetes/crds/machine.sapcloud.io_machineclasses.yaml, kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml, kubernetes/crds/machine.sapcloud.io_machines.yaml, kubernetes/crds/machine.sapcloud.io_machinesets.yaml, pkg/apis/machine/v1alpha1/machine_types.go, pkg/apis/machine/v1alpha1/machineclass_types.go, pkg/apis/machine/v1alpha1/shared_types.go, pkg/openapi/openapi_generated.go
This PR fixes the CRD manifests for several objects that use `metav1.ObjectMeta` or `runtime.RawExtension`. It's necessary to set `x-kubernetes-preserve-unknown-fields: true` for these types because otherwise data underneath related fields is pruned and leads to validation errors in MCM.
Example:
```
I0824 09:05:30.777736       1 machine_controller_util.go:366] List machines failed on decodeProviderSpecAndSecret: machine codes error: code = [Internal] message = [Error while validating ProviderSpec [spec.disks: Required value: at least one disk is required spec.machineType: Required value: machineType is required spec.region: Required value: region is required spec.zone: Required value: zone is required spec.networkInterfaces.networkInterfaces: …
```
=> Fix CRD manifests

pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/machineclass_types.go
This PR will add the new `*expectedNodeDetails` field to the `MachineClass` API for generic scale from zero implementation in CA
Fixes [#98](https://github.com/gardener/autoscaler/issues/98)
```feature user
Added *expectedNodeDetails field to the MachineClass API
```
=> added expectedNodeDetails field

.ci/test, pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machineutils/utils.go
This PR implements the logic for user triggered machine object deletion with which the user can easily replace a faulty node/unwanted node in the cluster by annotating the node with `node.machine.sapcloud.io/trigger-deletion-by-mcm="true"`
Fixes #390 
The changes are introduced only in out of tree machine controller as the in tree machine controller shall be deprecated soon.
```feature user
End User can now delete the backing machine object of the node instantly by annotating the desired node with  'node.machine.sapcloud.io/trigger-deletion-by-mcm="true"`
```
=> Logic for user triggered machine deletion

pkg/test/integration/common/framework.go, pkg/test/integration/common/helpers/machine_resources.go
This PR improves the integration test suite's test case by adding another wait condition for the test machine object to be deleted. This is being added to make the tests more elegant though it is identified because of the significant impact in Azure.
Fixes #
I vendored these changes in the MCM-Provider-Azure and executed the Integration test. The test case in the context now works as expected.
```other developer
NONE
```
=> IT suite waits to delete machine object

Makefile
/kind bug
`./docs/deployment/kubernetes.md#build-the-docker-image` states that `make docker-image` is the corresponding target.
```
make docker-image IMAGE_REPOSITORY=$REPOSITORY IMAGE_TAG=$TAG
make: Nothing to be done for `docker-image'.
```
```other operator
NONE
```
=> Fix target name in Makefile

pkg/test/integration/common/framework.go
for IT the env variable `CONTROL_CLUSTER_NAMESPACE` can remain unset(it can be set explicitly though by user) even when the code interprets the value of cluster namespace. 
But in some other parts of code to know the cluster namespace its beneficial if `CONTROL_CLUSTER_NAMESPACE` is set.
This PR sets the env variable.
Fixes #
```other operator
NONE
```
=> Set `CONTROL_CLUSTER_NAMESPACE` env variable for integration tests

kubernetes/deployment/in-tree/control-cluster-role.yaml, kubernetes/deployment/out-of-tree/control-cluster-role.yaml, pkg/util/client/leaderelectionconfig/config.go
CC: @ialidzhikov 
```other operator
The default leader election resource lock of `machine-controller-manager` has been changed from `endpoints` to `endpointsleases`.
```
```breaking operator
Components that deploy the `machine-controller-manager` will now have to adapt the RBAC rules to allow `machine-controller-manager` to maintain its leader election resource lock in `leases` as well.
```
=> Switch leader election to endpointleases

pkg/controller/machineset.go, pkg/controller/machineset_test.go
The machineSet finalizer update now has a backoff mechanism. The update will be tried 2 times by default and after that the object will be requeued with a backoff. The backoff is controlled by the rate limiting queue.
The error log is also improved.
Fixes #651 
```bugfix dependecy
MachineSet finalizer update is now done with a backoff. Earlier endless retries until success used to happen.
```
=> Retry with Backoff for machineset finalizer update

pkg/util/provider/machinecontroller/controller.go, pkg/util/provider/machinecontroller/machine_safety.go, pkg/util/provider/machinecontroller/machine_safety_test.go
Till now orphan collection triggers on machine obj deletion or after 30min.
But to handle cases which arise due to eventual inconsistency in AWS , where multiple VMs can start backing a machine obj, in that case to stop machine-controller to reach the VM quota , orphan collection is now also triggered if machine object is updated with a `OutOfRange` error description.
The update of machine obj to `OutOfRange` can only happen by `GetMachineStatus` call , which is called only during a machine creation or deletion.
So in summary , orphan collection will be triggered in three cases now
* during creation if multiple VM are seen
* during deletion
* after 30min of last logic run for each machine object.
Fixes #
**Special …
=> Trigger orphan collection on OutOfRange machine status

pkg/controller/machine.go, pkg/util/provider/machinecontroller/machine_util.go
/area ops-productivity
Fixes #671
```other operator
machine-controller-manager does now log the Node conditions when it considers Machine as unhealthy (and changes its state to `Unknown`).
```
=> Log Node conditions when Machine is considered as unhealthy

kubernetes/crds/machine.sapcloud.io_machines.yaml, pkg/apis/machine/v1alpha1/machine_types.go
This PR enhances CRD so that on `k get machines` the nodeName is also printed. This is to ease getting nodeName for provider like aws
Fixes #
```operator other
NONE
```
=> Node Name column while printing machine objects

kubernetes/crds/machine.sapcloud.io_machineclasses.yaml, pkg/apis/machine/v1alpha1/machineclass_types.go
`CredentialSecretRef` doesn't require `x-kubernetes-preserve-unknown-fields: true` field in machineClass CRD. Its removed using this PR.
Fixes #
Refer to [this](https://github.com/gardener/gardener/pull/5266#discussion_r784038131) discussion for reason.
```other operator
```
=> Remove PreserveUnknown field of CredenetialSecretRef

pkg/util/provider/machinecontroller/machine.go
There was a log which is improved. That log could confuse that a new VM is created (in cases where VM doesn't become available to Get call instantly)
Fixes #
```other operator
NONE
```
=> CreateMachine logs improved

pkg/controller/deployment_util.go
The annotation value of scale down annotation provided by CA has been changed from `True` to `true`. This will enable MCM to stop CA from scaling down during rolling update of machines.
Fixes #
```bugfix user
The value for key `cluster-autoscaler.kubernetes.io/scale-down-disabled` placed by MCM is now `true` and not `True`. This typo stopped MCM from disabling CA from scaling down during rolling update.
```
=> Scale down annotation value corrected

pkg/controller/autoscaler/types.go, pkg/controller/deployment_recreate.go, pkg/controller/deployment_rolling.go, pkg/controller/deployment_rolling_test.go, pkg/controller/deployment_util.go, pkg/util/provider/machinecontroller/machine_util.go, pkg/util/provider/machinecontroller/machine_util_test.go
Refactors autoscaler annotations to a separate package. This is necessary because with the inclusion of https://github.com/gardener/machine-controller-manager/pull/683 build targets for mcm-extensions that  depend on https://github.com/gardener/machine-controller-manager/tree/master/pkg/util/provider/app to start the machine controller will now include `gardener/machine-controller-manager/tree/master/pkg/driver` in their build.
This is problematic because the extensions now have a dependency on the infrastructure provider clients bundled with MCM that may conflict with their versions. It is better if this import chain is eliminated.
Fixes #
```other operator …
```
=> Refactor ClusterAutoscaler annotations to a separate package

pkg/controller/autoscaler/types.go, pkg/controller/deployment_recreate.go, pkg/controller/deployment_rolling.go, pkg/controller/deployment_rolling_test.go, pkg/controller/deployment_util.go, pkg/util/provider/machinecontroller/machine_util.go, pkg/util/provider/machinecontroller/machine_util_test.go
Cherry-pick of https://github.com/gardener/machine-controller-manager/pull/697
Fixes #
```other operator
Refactor autoscaler annotation to a separate package
```
=> Automated cherry pick of #697: Refactor ClusterAutoscaler annotations to a separate package

pkg/test/integration/common/framework.go
Adds an annotation to stop scaling up of MCM automatically by Dependency-watchdog during integration tests.
Fixes #
```other developer
MCM is annotated to ignore scaling by DWD during IT. Annotation is removed after the tests
```
=> Annotate mcm during Integration Tests

.ci/build, .ci/pipeline_definitions, Dockerfile, Makefile
This PR lets the CI pipeline build multi-arch images with support for `linux/amd64` and `linux/arm64`.
/area delivery
Fixes parts of https://github.com/gardener/gardener/issues/6258
The `build` steps have been unified along the way, i.e. `make build` builds the MCM binary locally for the system the build is executed on and `make docker-image` builds the MCM binary within the docker image. There is no dedicated local linux/amd64 build anymore as I didn't see any benefit of keeping it. Please let me know if you think otherwise.
```other operator
Published docker images for Machine-Controller-Manager are now multi-arch ready. They support …
```
=> Build Multi-Arch Images 📦

pkg/controller/controller_suite_test.go, pkg/util/provider/machinecontroller/machine_util.go, pkg/util/provider/machinecontroller/machine_util_test.go
A bug where MCM was not marking machine as failed during rollout has been resolved.
In situation where the all the machines in the new or the old machineset go into `Unknown` state , as per the current logic the rollout would stop and won't proceed until we manually delete the machine.
This happens because machineSet controller is not aware of a `Unknown` state and so takes no action, and only machine controller could resolve this situation by marking the machine `Failed`.
Fixes #
- this erroneous behavior was introduced recently as a part of the meltdown fix [PR](https://github.com/gardener/machine-controller-manager/pull/683) , to avoid making meltdown logic clash with the …
=> Mark machine failed during rollout also

pkg/controller/deployment_test.go
A unit test has been removed which checks adding `scale-down-disabled` annotation during rollout by MCM
It was flaky hence removed.
Fixes #
```other operator
NONE
```
=> Removed flaky test case

kubernetes/deployment/in-tree/control-cluster-role.yaml, kubernetes/deployment/in-tree/target-cluster-role.yaml, kubernetes/deployment/out-of-tree/control-cluster-role.yaml, kubernetes/deployment/out-of-tree/target-cluster-role.yaml, pkg/util/client/leaderelectionconfig/config.go
Part of https://github.com/gardener/gardener/issues/4742
/cc @ialidzhikov 
```breaking operator
The default leader election resource lock of `machine-controller-manager` has been changed from `endpointsleases` to `leases`.
Please make sure, that you had at least `machine-controller-manager@v0.43.0` running before upgrading to `v0.46.0`, so that it has successfully acquired leadership with the hybrid resource lock (`endpointsleases`) at least once.
```
=> Migrate leader election to leases

kubernetes/deployment/in-tree/control-cluster-role-binding.yaml, kubernetes/deployment/in-tree/control-cluster-role.yaml, kubernetes/deployment/in-tree/target-cluster-role-binding.yaml, kubernetes/deployment/in-tree/target-cluster-role.yaml, kubernetes/deployment/out-of-tree/control-cluster-role-binding.yaml, kubernetes/deployment/out-of-tree/control-cluster-role.yaml, kubernetes/deployment/out-of-tree/target-cluster-role-binding.yaml, kubernetes/deployment/out-of-tree/target-cluster-role.yaml, pkg/test/integration/common/helpers/handling_files.go
This PR updates the rule for leases in cluster role and moves clusterroles/clusterrolebindings to v1 from v1beta1. This is needed for the mcm-provider IT to work when running the controllers inside a cluster and not as a local process. 
Fixes #674 
```bugfix operator
resourceName `machine-controller` added for leases in clusterrole. Updated version of Clusterroles and Clusterrolebindings to v1.
```
=> Update version of clusterroles, add resoureName for leases

kubernetes/deployment/in-tree/control-cluster-role-binding.yaml, kubernetes/deployment/in-tree/control-cluster-role.yaml, kubernetes/deployment/in-tree/target-cluster-role-binding.yaml, kubernetes/deployment/in-tree/target-cluster-role.yaml, kubernetes/deployment/out-of-tree/control-cluster-role-binding.yaml, kubernetes/deployment/out-of-tree/control-cluster-role.yaml, kubernetes/deployment/out-of-tree/target-cluster-role-binding.yaml, kubernetes/deployment/out-of-tree/target-cluster-role.yaml, pkg/test/integration/common/helpers/handling_files.go
Updates the rule for leases in cluster role and moves clusterroles/clusterrolebindings to v1 from v1beta1. This is needed for the mcm-provider IT to work when running the controllers inside a cluster and not as a local process.
Fixes #
```bugfix operator
resourceName `machine-controller` added for leases in clusterrole. Updated version of Clusterroles and Clusterrolebindings to v1.
```
=> Cherry-pick of PR #738

pkg/controller/machine_bootstrap_token.go, pkg/util/provider/machinecontroller/machine_bootstrap_token.go
In metal-stack we do not use the wide-spread software [cloud-init](https://cloud-init.io/) for preparing cloud instances but [Ignition](https://coreos.github.io/ignition/). The Ignition userdata format encodes data with URL scheme, such that special characters are not contained in user-given contents of the userdata.
The current code patches a placeholder `<<BOOTSTRAP_TOKEN>>` in order to enrich the userdata with a node's bootstrap token. As the placeholder contains special characters, the string replacement does not work for Ignition-formatted userdata, which looks like:
```
...
"path":"/var/lib/cloud-config-downloader/credentials/bootstrap-token","contents":{"source":"data:,%3C%3CBOOTSTRAP_TOKEN%3E%3E","verification":{}}
...
```
This PR allows …
=> Support URL encoded bootstrap token replacement

Makefile, docs/documents/apis.md, kubernetes/crds/machine.sapcloud.io_alicloudmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_awsmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_azuremachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_gcpmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_machineclasses.yaml, kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml, kubernetes/crds/machine.sapcloud.io_machines.yaml, kubernetes/crds/machine.sapcloud.io_machinesets.yaml, kubernetes/crds/machine.sapcloud.io_openstackmachineclasses.yaml, kubernetes/crds/machine.sapcloud.io_packetmachineclasses.yaml, pkg/apis/machine/v1alpha1/machine_types.go
WIth this PR, when one runs the` kubectl get machines` command,`Node name` will be displayed as a column. If the `-owide` option is used then `ProviderID` will also be displayed as a column. The output will be as follows:
Fixes #737 
```feature operator
Using `kubectl get machines` will display `Node` of the corresponding machine as a column. If `-owide` flag is used then the corresponding `ProviderID` will also be displayed.
```
=> Add nodeName and providerID column while listing machines(s)

docs/documents/apis.md, kubernetes/crds/machine.sapcloud.io_machineclasses.yaml, kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml, kubernetes/crds/machine.sapcloud.io_machines.yaml, kubernetes/crds/machine.sapcloud.io_machinesets.yaml, pkg/apis/machine/v1alpha1/machine_types.go, pkg/apis/machine/v1alpha1/machineclass_types.go, pkg/apis/machine/v1alpha1/machinedeployment_types.go, pkg/apis/machine/v1alpha1/machineset_types.go, pkg/openapi/openapi_generated.go
This PR adds short names for `machine`, `machineclass`, `machinedeployment` and `machineset` resources. The abbreviations are as follows:
1. mach -> machines.
2. machcls -> machineclass
3. machdeploy -> machinedeployment
4. machset -> machineset
Fixes #
The testing was done by running IT on dev cluster with `mcm` and `mcm-provider-aws` run locally.
```feature operator
Added new short names for machine(mach), machineClass(machcls), machineDeployment(machdeploy), and machineSet(machset) resources.
```
=> Add short names for `Machine`, `MachineClass`, `MachineDeployment` and `MachineSet` resources

kubernetes/crds/machine.sapcloud.io_machineclasses.yaml, pkg/apis/machine/v1alpha1/machineclass_types.go
This PR updates the short name of `machineclass` resource from `machcls` to `machclass`.
Fixes #
```feature operator
Machine class short name changed to `machclass` from `machcls` 
```
=> Change short name of `Machineclass` from `machcls` to `machclass`

kubernetes/crds/machine.sapcloud.io_machineclasses.yaml, kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml, kubernetes/crds/machine.sapcloud.io_machines.yaml, kubernetes/crds/machine.sapcloud.io_machinesets.yaml, pkg/apis/machine/v1alpha1/machine_types.go, pkg/apis/machine/v1alpha1/machineclass_types.go, pkg/apis/machine/v1alpha1/machinedeployment_types.go, pkg/apis/machine/v1alpha1/machineset_types.go
This PR updates the short names for `Machine`, `MachineClass`, `MachineDeployment` and `MachineSet` resources. The new and final ones are as follows:
1. `mc` - `machine`
2. `mcc` - `machineClass`
3. `mcd` - `machineDeployment`
4. `mcs` - `machineSet`
Fixes #
```feature operator
Added new short names for machine(mc), machineClass(mcc), machineDeployment(mcd), and machineSet(mcs) resources.
```
=> Update short names for `Machine`, `MachineClass`, `MachineDeployment` and `MachineSet` resources

pkg/apis/machine/v1alpha1/machinedeployment_types.go, pkg/controller/deployment_progress.go, pkg/controller/deployment_sync.go, pkg/controller/machine_safety.go
Currently when `progressDeadlineSeconds` is nil , then no `Progressing` condition is added to machineDeployment. This PR adds that condition now. 
In gardener, currently we deploy machineDeployments with this field as `nil` , but we would also like to see if the deployment is rollingUpdating or not. Now that this condition would be present, we could achieve that.
Fixes #
- done as a pre-step for solving https://github.com/gardener/machine-controller-manager/issues/754
```feature user
MachineDeployment would now have `Progressing` condition even when no progress Deadline is specified. This condition would never go to the reason `ProgressDeadlineExceeded` in that …
```
=> Update `Progressing` condition on machineDeployment for nil `progressDeadlineSeconds`

pkg/controller/controller.go, pkg/controller/controller_suite_test.go
Fix for `make start` bug where secrets hasSynced function was nil
https://github.com/gardener/machine-controller-manager/issues/622
Bug fix where a change was missed.
```other operator
NONE
```
=> Remove secrets queue and secretSynced MCM usage

.ci/pipeline_definitions
Add cve categorization for MCM.
The categorization was initially defined here and it transferred as defined to the MCM repository: 
- https://github.com/gardener/gardener-extension-provider-aws/pull/684
- https://github.com/gardener/gardener-extension-provider-gcp/pull/546
- https://github.com/gardener/gardener-extension-provider-azure/pull/621
- https://github.com/gardener/gardener-extension-provider-openstack/pull/553
- https://github.com/gardener/gardener-extension-provider-alicloud/pull/562
- https://github.com/gardener/gardener-extension-provider-vsphere/pull/362
We move the cve categorization to the MCM repository as the categorization can't be taken into consideration when it is defined in the respective provider extension project. Once this …
=> Add cve categorization for mcm

pkg/controller/controller_suite_test.go, pkg/controller/deployment_sync.go, pkg/controller/deployment_sync_test.go, pkg/controller/machineset.go, pkg/test/integration/common/framework.go
Fixes #802 
```bugfix user
An edge case where all the machineSets were scaled down to zero has been dealt with.
```
=> Edge cases corrected where all machineSets were scaling down to zero

docs/documents/apis.md, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/machine_types.go, pkg/client/clientset/internalversion/clientset.go, pkg/client/clientset/internalversion/typed/machine/internalversion/fake/fake_machine.go, pkg/client/clientset/internalversion/typed/machine/internalversion/fake/fake_machineclass.go, pkg/client/clientset/internalversion/typed/machine/internalversion/fake/fake_machinedeployment.go, pkg/client/clientset/internalversion/typed/machine/internalversion/fake/fake_machineset.go, pkg/client/clientset/internalversion/typed/machine/internalversion/fake/fake_machinetemplate.go, pkg/client/clientset/internalversion/typed/machine/internalversion/machine_client.go, pkg/client/clientset/versioned/clientset.go, pkg/client/clientset/versioned/typed/machine/v1alpha1/fake/fake_machine.go, pkg/client/clientset/versioned/typed/machine/v1alpha1/fake/fake_machineclass.go, pkg/client/clientset/versioned/typed/machine/v1alpha1/fake/fake_machinedeployment.go, pkg/client/clientset/versioned/typed/machine/v1alpha1/fake/fake_machineset.go, pkg/client/clientset/versioned/typed/machine/v1alpha1/machine_client.go, pkg/client/informers/externalversions/factory.go, pkg/client/informers/internalversion/factory.go, pkg/openapi/openapi_generated.go, pkg/util/provider/app/options/options.go, pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go
This PR turns `CLBF` machines to `Pending` if the `driver.CreateMachine` call was successful in the previous reconciliation. This will help the `reconcileMachineHealth` to turn the `Pending` to the `Running` phase when the machine is reconciled due to node object creation. 
Fixes #805 
```other operator
`CrashloopBackoff` machines will turn to `Running` quicker
```
=> Turn `CrashloopBackoff` machines to `Running` quicker

pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/machine_types.go, pkg/util/provider/app/options/options.go, pkg/util/provider/machinecontroller/machine.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go
This PR turns `CLBF` machines to `Pending` if the `driver.CreateMachine` call was successful in the previous reconciliation. This will help the `reconcileMachineHealth` to turn the `Pending` to the `Running` phase when the machine is reconciled due to node object creation. 
Fixes #805 
```bugfix user
`CrashloopBackoff` machines will turn to `Running` quicker .
```
=> Automated cherry pick of #806: Turn `CrashloopBackoff` machines to `Running` quicker

pkg/controller/deployment_sync.go
This PR fixes a nil pointer panic and does some housekeeping job.
Fixes #
```bugfix operator
An issue causing nil pointer panic on scaleup of the machinedeployment along with trigger of rolling update, is fixed
```
=> Automated cherry pick of #814: Fix nil pointer panic

pkg/controller/deployment_sync.go, pkg/controller/deployment_sync_test.go
Fixes #815 
```bugfix user
An edge case where outdated DesiredReplicas annotation blocked a rolling update is fixed.
```
=> Keep `DesiredReplicas` annotation up to date even if no scaling happens

pkg/controller/deployment_sync.go, pkg/controller/deployment_sync_test.go
Fixes #815 
```bugfix user
An edge case where outdated DesiredReplicas annotation blocked a rolling update is fixed.
```
=> Automated cherry pick of #821: keep desired replicas annotation up to date even if no

.docforge/manifest.yaml, README.md, docs/README.md, docs/deployment/_index.md, docs/deployment/kubernetes.md, docs/development/_index.md, docs/development/local_setup.md, docs/documents/_index.md, docs/proposals/_index.md, docs/todo/_index.md, docs/usage/_index.md
This PR updates the file structure in the Machine controller Manager section of the public Gardener website, implementing the changes asked for in #829. It is connected to a [PR in gardener/documentation](https://github.com/gardener/documentation/pull/417) that modifies the manifest file there.
Fixes #
```doc developer
NONE
```
=> Updated the docforge manifest & added index files

pkg/controller/deployment_util.go
Includes `UnavailableReplicas` in determining if the status of machine deployment needs to be updated.
Fixes #832 
```bugfix operator
Included `UnavailableReplicas` in determining if a machine deployment status update is needed
```
=> Include `UnavailableReplicas` in MCD status update check

pkg/controller/deployment_util.go
/kind bug
Cherry pick of #833 on rel-v0.49.
#833: include unavailable replicas in mcd status update check
**Release note:**
```bugfix operator
Included `UnavailableReplicas` in determining if a machine deployment status update is needed
```
=> [rel-v0.49] Automated cherry pick of #833: include unavailable replicas in mcd status update check

pkg/controller/deployment_util.go
```
{"log":"(SetReplicasAnnotations) ms.Name: shoot--foo--bar-default-z3-797b7 desired: 0 , max: 0 , updated: %!d(bool=true)","pid":"1","severity":"INFO","source":"deployment_util.go:615"}
```
The `updated` var is boolean, hence `%t` should be used instead of `%d`. Ref https://pkg.go.dev/fmt
N/A
N/A
```other operator
NONE
```
=> Nit: Fix the format verb

pkg/util/provider/machinecodes/status/status.go, pkg/util/provider/metrics/metrics.go
Two new metrics have been introduced
- Duration of all successful provider API calls
- Total duration taken to execute [Driver](https://github.com/gardener/machine-controller-manager/blob/dbbaa4526084d2d5e5d210721be186a5ee72c68f/pkg/util/provider/driver/driver.go#L28-L39) methods.
In addition to the metrics, `status.Status` has been enhanced to capture the underline `cause error`. A convenience function `WrapError` has also been added which captures the underline cause. This will help consumers(mcm provider implementations) to introspect the error to extract underline error code, especially during writing unit tests
Fixes #841 
```other operator
New metrics …
```
=> Introduce new metrics to track API call duration and Update status.Status to capture underlying cause

.env, Makefile, docs/development/integration_tests.md, hack/gardener_local_restore.sh, hack/non_gardener_local_restore.sh
This PR updates the documentation of Integration tests and moves the dynamic content of Makefile to the .env file.
Fixes #846
```other operator
NONE
```
=> Updated docs of IT and Moved Dynamic content from Makefile to .env file.

pkg/test/integration/common/framework.go
This PR fixes the rotation of Log files issue on multiple runs of Integration tests. 
Fixes:- Part of #853 
```other operator
NONE
```
=>  Fix Rotation of log files in IT

pkg/util/provider/app/options/options.go, pkg/util/provider/machinecontroller/machine_safety.go, pkg/util/provider/machinecontroller/machine_safety_test.go, pkg/util/provider/machinecontroller/machine_safety_util.go, pkg/util/provider/machinecontroller/machine_safety_util_test.go
See https://github.com/gardener/machine-controller-manager/issues/863
Fixes #863 
```bugfix operator
Removes `node.machine.sapcloud.io/not-managed-by-mcm` annotation from nodes managed by the MCM.
```
```other operator
The default `machine-safety-orphan-vms-period` has been reduced from 30m to 15m.
```
=> Remove NotManagedByMCM when not applicable

docs/development/integration_tests.md, pkg/test/integration/common/framework.go, pkg/test/integration/common/helpers/cluster.go
This PR removes the dependency on kubeconfig for identifying the control cluster as seed and also, updates the integration tests documentation.
Fixes part of #853 
```other operator
NONE
```
=> Remove Kubeconfig dependency for verification of control cluster in IT

.ci/pipeline_definitions, Makefile, kubernetes/deployment/out-of-tree/deployment.yaml
GCR has been deprecated [0] in favour of Artifact-Registry.
Thus, change push-targets for OCI-Images:
- europe-docker.pkg.dev/gardener-project/snapshots for snapshots
- europe-docker.pkg.dev/gardener-project/releases for releases
- europe-docker.pkg.dev/gardener-project/public for combined view of snapshots + releases
In addition, switch testmachinery-Image to new location in Artifact-Registry.
[0]
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr
```breaking operator
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.
```
=> switch GCR -> Artifact-Registry

pkg/test/integration/common/framework.go
This PR fixes the issue where MCM was unable to restart during cleanup which lead to cleanup failure
Fixes #
The logs for the restarted MCM and MC will now be appended to the existing logs itself.
```other operator
NONE
```
=> Fixed MCM restart during cleanup

hack/api-reference/generate-spec-doc.sh
This PR installs the binary for the gen-crd-api-reference-docs each time so it is now platform independent.
Fixes #694 
```other operator
NONE
```
=> Made the gen-crd-api-reference-docs binary platform independent

pkg/util/k8sutils/version.go
The version format of GKE clusters is $K8S_VERSION-gke.$INTERNAL_NUMBER (e.g., 1.27.9-gke.300). This format is not fully compliant to the SEMVER spec and causes [this library](https://github.com/Masterminds/semver/) to mistakenly recognize, for example, a 1.27.9-gke.300 cluster to be older than 1.21. This is a known issue (e.g., https://github.com/helm/helm/issues/3810), and this change updates the version constraint to properly support GKE versions.
N/A
N/A
NONE
=> Support checking GKE version schema

docs/development/integration_tests.md, pkg/test/integration/common/framework.go
This PR introduces a new env var `TARGET_RESOURCE_GROUP`
This PR also corrects the use of `IS_CONTROL_CLUSTER_SEED` in the docs
Fixes #
```other operator
NONE
```
=> Env var  for IT tests

pkg/util/provider/machinecontroller/machine_util.go
When a Node is never associated with its Machine. Ie the machine object never has the `machine.Labels[v1alpha1.NodeLabelKey]` set after the machine creation, then during the deletion flow, our Node object is not deleted. (Label updation can be missed if the machine object update transiently fails)
Then after some time, the dangling Node object gets the `NotManagedByMCM` annotation.
Fixes #875
```bugfix operator
Fix for edge case of Node object deletion missed during machine termination.
```
=> Check, update node label on machine obj prior to drain,termination

docs/documents/apis.md, kubernetes/crds/machine.sapcloud.io_machineclasses.yaml, pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/machineclass_types.go, pkg/apis/machine/v1alpha1/zz_generated.conversion.go, pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go, pkg/apis/machine/zz_generated.deepcopy.go, pkg/openapi/openapi_generated.go
This PR adds `architecture` field in the node template
Fixes part of #https://github.com/gardener/autoscaler/issues/122
```other operator
Architecture field added in the nodetemplate. This will allow CA to pickup architecture from machine class and schedule pods on relevant arch nodes.
```
=> Added `Architecture` in NodeTemplate

Makefile, docs/development/integration_tests.md, hack/gardener_local_setup.sh, hack/non_gardener_local_setup.sh
This PR modifies the IT test `make` target to incorporate `shoot as a seed setup` as well as `seed setup` for local IT.
Fixes #
```other operator
NONE
```
=> Enhanced local IT setup

pkg/util/provider/drain/drain.go, pkg/util/provider/machinecontroller/machine_util.go
This PR introduces a drain Context in `RunDrain` with a timeout so that context cancels and machine can be force deleted later.
Fixes #785 
```other operator
Drain timeout is now correctly honored for Pod eviction during Machine Drain
```
=> Improved context with timeout for DrainNode

docs/documents/apis.md, hack/api-reference/providerspec-config.json, hack/api-reference/template/members.tpl, hack/api-reference/template/type.tpl, pkg/client/informers/externalversions/factory.go, pkg/openapi/openapi_generated.go
This PR fixes the API spec doc in `docs/documents/apis.md`
Fixes #918 
```doc operator
Broken API doc links are now fixed
```
=> Fix API doc

.gitignore, Makefile, hack/gardener_local_setup.sh, pkg/util/provider/machinecontroller/machine_util.go
This PR fixes the `triggerDeletionFlow`, specifically the  `getVMStatus` function to allow deletion of Unitialized VMs to proceed 
Fixes #926 
```bugfix operator
Fixed a bug where the `Unitialised` error code was blocking machine deletion
```
=> Allow deletion to proceed in case of VM initialization error

.gitignore, Makefile, hack/gardener_local_setup.sh, pkg/util/provider/machinecontroller/machine_util.go
* allow deletion to proceed in case of VM initialization error
* omit tool binaries
* set_makefile_env: addec CONTROL_NAMESPACE, LEADER_ELECT
---------
Fixes #
```bugfix operator #928 @rishabh-11 
Fixed a bug where the `Unitialised` error code was blocking machine deletion
```
=> [Cherry-pick rel-v0.53] Allow deletion to proceed in case of VM initialization error (#928)

pkg/util/provider/machinecontroller/machine_safety.go
Add namespace to dummy machine object so that driver can rely on the namespace being set.
Some drivers may assume that the namespace of the machine resources is correctly set when a request is sent to them, e.g. see https://github.com/gardener/gardener/pull/10176. As the namespace of the machine is known due to its machine class, it should be always safe to set the correct namespace.
Fixes #
```other operator
```
=> Add namespace to dummy machine object so that driver can rely on the namespace being set

hack/gardener_local_setup.sh
This PR fixes a bug where the `shoot--` prefix was not added to the control cluster namespace in the gardener local setup case.
Control cluster namespaces in gardener always start with `shoot--` prefix. This was erroneously removed in #928. 
Fixes #
```bugfix developer
Fixed bug that removed the shoot-- prefix from control cluster namespace for integration tests using the gardener local setup case
```
=> Fix gardener_local_setup script to use correct control cluster namespace

pkg/util/provider/drain/drain.go, pkg/util/provider/drain/drain_test.go
/kind bug
When draining nodes, MCM already ignores provider-unrelated PVs when waiting for the detachments.
However, it does wait for such PVs to reattach to other nodes until running into a timeout.
This PR ensures that the same filter of the driver is used for tracking reattachments of PVs as well.
For example, when draining nodes where NFS volumes are used, MCM would wait for the reattachment of these volumes.
There is no such thing as an attachment to a node for NFS volumes. NFS volumes only need to be mounted (by kubelet).
Accordingly, MCM always runs into the configured PV reattach timeout, if there are pods with NFS PVCs on the to-be-drained node.
This prolongs the drain operation of such nodes severely. …
=> Don't track reattachment of provider-unrelated PVs

pkg/util/provider/machinecontroller/userdata.go
This PR exports the magic userdata strings `<<BOOTSTRAP_TOKEN>>` and `<<MACHINE_NAME>>` that they can be reused by `gardener/gardener`.
Fixes #
```other operator
NONE
```
=> Export magic userdata strings

.ci/check, .gitignore, Makefile, cmd/machine-controller-manager/app/controllermanager.go, hack/sast.sh, hack/tools.mk, hack/tools/install-gosec.sh, pkg/apis/machine/validation/machinedeployment.go, pkg/controller/controller_utils.go, pkg/controller/deployment_machineset_util.go, pkg/controller/deployment_rolling.go, pkg/controller/deployment_sync.go, pkg/controller/deployment_util.go, pkg/controller/machine_safety.go, pkg/test/integration/common/framework.go, pkg/test/integration/common/helpers/handling_files.go, pkg/test/integration/common/helpers/nodes.go, pkg/util/hash/hash.go, pkg/util/provider/app/app.go, pkg/util/provider/machinecodes/status/status.go, pkg/util/provider/machinecontroller/userdata.go
This PR introduces two make targets: `sast` and `sast-report` to run `gosec` for Static Application Security Testing. Additionally, it also addresses the security vulnerabilities in the MCM repository. It uses the default ruleset of gosec from gardener/gardener as introduced in https://github.com/gardener/gardener/pull/9959. 
`sast-report` target has also been added as a dependency for the `check` target.
Partially fixes #948 
Tested manually to check if gosec is downloaded and installed to `hack/tools/bin`, if not already present, on running `make sast` and `make sast-report`.
Integration tests passed with provider-aws.
```other developer
Adding `gosec` for …
```
=> Introduce `gosec` for Static Application Security Testing (SAST)

Makefile, pkg/apis/machine/v1alpha1/machinedeployment_types.go, pkg/apis/machine/validation/machinedeployment.go, pkg/controller/controller_utils_test.go, pkg/controller/deployment_sync.go, pkg/test/integration/common/framework.go, pkg/test/integration/common/helpers/machine_resources.go
The PR adds a check to distinguish between a rolling update and a scale-from-zero scenario. Additionally, it also updates the integration tests to verify MCM's behaviour for the scenario.
Fixes #952 
Integration tests with mcm-provider-gcp passed successfully.
```bugfix user
MCM recognizes scaling-up of `machineDeployment` from 0 to more replicas as a scaling event rather than a rolling update.
```
=> Fix edge-case where scale-from-zero of MCD is mistaken for a rolling update

pkg/controller/deployment.go
This PR fixes a bug where a `nil` check was not performed before adding an annotation to a machine. 
Machines are not always guaranteed to have annotations, hence a `nil` check is required here
Fixes #
```other operator
```
=> Add a `nil` check before trying to adding mc annotation

pkg/controller/deployment.go
This PR cherry picks the following PR: https://github.com/gardener/machine-controller-manager/pull/966
Fixes #
```bugfix operator
A bug was fixed where MCM panics when trying to add an annotation to a nil map
```
=> [rel-v0.56] Add a nil check before trying to adding mc annotation (#966)

pkg/controller/controller_utils.go, pkg/controller/deployment_test.go, pkg/controller/deployment_util.go, pkg/controller/machineset.go, pkg/controller/machineset_test.go, pkg/controller/machineset_util.go, pkg/util/provider/machineutils/utils.go
Fixes #971
```bugfix operator
CA tainted node is removed as soon as possible by MachineSet controller 
```
=> Trigger removal of CA tainted machine without waiting for replica change

pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/machine_types.go, pkg/util/provider/machineutils/utils.go
This PR introduces constants for Conditions and Status for InPlace update scenarios.
Part of #944 
Part of https://github.com/gardener/gardener/issues/10219
This change was part of https://github.com/gardener/machine-controller-manager/pull/973. However, these constants are urgently required in the gardener/gardener PRs. Hence, we request an MCM patch release with these changes.
/invite @aaronfern @elankath @unmarshall
```other operator
NONE
```
=> [GEP-31] Introduce Constants needed for Conditons and Status for InPlace update 

pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/machine_types.go, pkg/util/provider/machineutils/utils.go
Cherry pick https://github.com/gardener/machine-controller-manager/pull/980
Fixes #
```other operator
NONE
```
=> [rel-v0.57] [GEP-31] Introduce Constants needed for Conditons and Status for InPlace update

pkg/apis/machine/types.go, pkg/apis/machine/v1alpha1/machinedeployment_types.go, pkg/util/provider/machinecontroller/machine_test.go, pkg/util/provider/machinecontroller/machine_util.go
Fixes #977 and #961
```other operator
Resource exhaustion on machine creation results in a longer retry period
```
=> Minor fixes

.ci/build, Makefile, cmd/machine-controller-manager/app/controllermanager.go, pkg/util/provider/app/app.go, pkg/version/version.go
Version information is not being logged at startup currently.
https://github.com/gardener/machine-controller-manager/blob/57dad3e97b4b0d18e576c8f3ec5ae3d17a062782/cmd/machine-controller-manager/app/controllermanager.go#L78
does not really print anything meaningful. Currently it prints the following:
```
I0416 03:47:56.984925       1 controllermanager.go:78] Version: v0.0.0-master+$Format:%H$
```
which is the template string present in [client-go@v0.31.0/pkg/version/base.go](https://github.com/kubernetes/client-go/blob/02a19c375c491042890be396d94a26a69da89563/pkg/version/base.go#L59). As described in the linked file a few lines above:
```
// If you are looking at these fields in the git tree, they look
// strange. They are modified on the fly by the …
```
=> Fix version logging at binary startup.

README.md, pkg/controller/controller_suite_test.go, pkg/controller/machineset.go, pkg/controller/machineset_test.go, pkg/util/provider/machinecontroller/machine.go
Upon failure in deletion of a machine, it should not transition to `Terminating` phase.
Fixes #984 
```bugfix operator
Fixed a bug in the MachineSet controller where the machine status was set to `Terminating` even if attempt to delete the machine object failed.
```
=> Don't update machine status to terminating on deletion failure

pkg/util/provider/machinecontroller/machine_util.go
Uses `strconv.ParseBool` instead of `"True"` to check the `force-deletion` Machine label.
=> fix: use `strconv.ParseBool` for `force-deletion` label

pkg/util/provider/machinecontroller/metrics.go, pkg/util/provider/metrics/metrics.go
This PR adds a new label `node_name` to the `mcm_machine_info` metric
Fixes #992
```other operator
add new label `node_name` to the `mcm_machine_info` metric
```
=> Add `node_name` label to the `mcm_machine_info` metric

Dockerfile, Makefile
This PR simplifies developing machine-controller-manager changes based on [gardener's local setup](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md).
Now, you can push an image to the local setup registry using:
```
make docker-image IMAGE_REPOSITORY=garden.local.gardener.cloud:5001/machine-controller-manager IMAGE_TAG=<optional-tag> PLATFORM=<e.g., linux/arm64> PUSH=true
```
Also, repetitive builds are much faster now (mounting a cache directory for the go build cache).
I used this while implementing https://github.com/gardener/machine-controller-manager/issues/994
```other developer
NONE
```
=> Simplify local development

pkg/controller/deployment_inplace.go, pkg/util/provider/machinecontroller/controller.go, pkg/util/provider/machinecontroller/machine_util.go
After a successful in-place update, the controller now adds the 'critical components not ready' taint to the node. This prevents pods from being scheduled until critical component pods are ready, improving node readiness handling.
Part of https://github.com/gardener/machine-controller-manager/issues/944
```other operator
`node.gardener.cloud/critical-components-not-ready` taint is added to the node after the successful in-place update to prevent scheduling any workload before critical component pods are ready.
```
=> Add taint for critical components not ready after update

pkg/controller/deployment_inplace.go, pkg/util/provider/machinecontroller/controller.go, pkg/util/provider/machinecontroller/machine_util.go
cherry pick for PR #1017
Fixes #
```other operator #1017 @acumino 
`node.gardener.cloud/critical-components-not-ready` taint is added to the node after the successful in-place update to prevent scheduling any workload before critical component pods are ready.
```
=> [rel-v0.59] Add taint for critical components not ready after update (#1017)

pkg/util/provider/machinecontroller/machine_util.go, pkg/util/provider/machinecontroller/machine_util_test.go
This PR fixes the bug in calculation of timeout check for `MachineCreationTimeout` when the machine is `Pending`. Earlier, the value `machine.Status.CurrentStatus.LastUpdateTime.Time` was being used, which would reset the timer and allow machine to stay in `Pending` for longer than intended. The check now uses `machine.CreationTimestamp.Time` to check if time out has occurred. The PR also changes the way in which other timeouts are checked in `reconcileMachineHealth` to improve readability. Unit tests have been corrected to reflect change made to the logic.
Fixes #1009 
IT for mcm-provider-aws and mcm-provider-gcp passed.
The changes made were tested locally by setting …
=> Fix checking of `MachineCreationTimeout` when machine is `Pending`

pkg/controller/deployment_machineset_util.go, pkg/controller/metrics.go
This PR adds changes such that a gauge metric scraped on prometheus gets cleared and re-populated on every poll, so that it reflects the latest state of the reference slice `*machineSet.Status.FailedMachines`.
The logic to set this variable has also been updated so that it contains the current set of machines in the `Failed` state.
Fixes #476 
IT for mcm-provider-aws passed
Testing was done by setting the `machineCreationTimeout` to a value lesser than the time it takes for a machine to be provisioned and move into the `Running` state (1m). The machine moves to the `Failed` state, when it can be checked against a prometheus graph to verify if it was recorded accurately
Some …
=> Fix `mcm_machine_set_failed_machines` metric to more accurately reflect current state

pkg/controller/deployment_inplace.go, pkg/controller/deployment_recreate.go, pkg/controller/deployment_rolling.go
This PR introduces log messages to indicate when rollout operations are ongoing for MachineDeployments and when nodes are being annotated with cluster autoscaler scale-down annotations.
Changes made for InPlace, Rolling and Recreate
Passed unit tests
```other operator
Add informational logging for MachineDeployment rollout events
```
=> Log rollout events
